<a href="https://colab.research.google.com/github/prateekbeh/algo_ds/blob/master/seismic_lwe4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from netCDF4 import Dataset as dt
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import matplotlib.dates as mdt
import matplotlib.gridspec as gridspec
from matplotlib.colorbar import Colorbar
from datetime import datetime
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.animation as anim
from shapely.geometry import Point , shape , Polygon
from dataclasses import dataclass, fields
import matplotlib.pyplot as pl
import hvplot.xarray
#import fiona
import shapefile
import geopandas as gpd
import rasterio
from rasterio.features import geometry_mask
import netCDF4 as nc
import math
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
from datetime import date
import geopandas as gpd
import numpy as np
from shapely.geometry import Polygon, MultiPolygon, Point

ModuleNotFoundError: No module named 'netCDF4'

In [ ]:
!pip install rasterio

In [2]:

from google.colab import drive
drive.mount('/content/drive')

# Load the catalog data from Google Drive
file_path = '/content/drive/MyDrive/grace_data/catalog.txt'
catalog_data = pd.read_csv(file_path, delim_whitespace=True)

# OLD CODE START

# OLD CODE END

# New Step 1: Convert the date column to datetime format
catalog_data['date'] = pd.to_datetime(catalog_data['date'], format='%Y-%m-%d')

# Filter seismic data starting from 2022-04
catalog_data = catalog_data[catalog_data['date'] >= '2002-04-01']
catalog_data = catalog_data[catalog_data['mag'] >= 5]


# New Step 2: Divide the dataset into a grid of 0.5 x 0.5 degree
# Round the latitude and longitude to the nearest 0.25 or 0.5
catalog_data['lat_grid'] = np.where((catalog_data['latitude'] % 1) < 0.5,
                                    np.floor(catalog_data['latitude']) + 0.25,
                                    np.floor(catalog_data['latitude']) + 0.75)

catalog_data['lon_grid'] = np.where((catalog_data['longitude'] % 1) < 0.5,
                                     np.floor(catalog_data['longitude']) + 0.25,
                                     np.floor(catalog_data['longitude']) + 0.75)

Mounted at /content/drive

<ipython-input-2-dcca60911d15>:6: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  catalog_data = pd.read_csv(file_path, delim_whitespace=True)

In [3]:
# prompt: iterate through the catalog data and implement a formula. Given the mag(in mw) , obtain D_eps = 10^(0.442M-2.73)/(eps)^1/3 , where eps = 10^-8

# Assuming 'mag' column exists in your catalog_data DataFrame

eps = 10**-8
catalog_data['D_eps'] = 10**(0.442 * catalog_data['mag'] - 2.73) / (eps**(1/3))

In [4]:
# prompt: Implement one more formula, for catalog data, i.e. log (D_eps * T) = 0.63 * mag +- 0.15, get the value of T. the log is base 10

# Calculate T using the formula log(D_eps * T) = 0.63 * mag +- 0.15
# We'll consider both the + and - cases for the uncertainty

catalog_data['T_plus'] = 10**(0.63 * catalog_data['mag'] + 0.15) / catalog_data['D_eps']
catalog_data['T_minus'] = 10**(0.63 * catalog_data['mag'] - 0.15) / catalog_data['D_eps']

# Calculate the mean of T
catalog_data['T'] = (catalog_data['T_plus'] + catalog_data['T_minus']) / 2

In [5]:
catalog_data

,date,time,latitude,longitude,depth,mag,magtype,lat_grid,lon_grid,D_eps,T_plus,T_minus,T
27321,2002-06-17,16:55:07.680Z,40.809833,-124.552000,17.195,5.20,mw,40.75,-124.75,171.817212,15.521487,7.779171,11.650329
27743,2003-12-22,19:15:56.240Z,35.700500,-121.100500,8.382,6.50,mw,35.75,-121.25,645.158861,27.247919,13.656309,20.452114
28206,2004-09-18,23:02:17.750Z,38.009500,-118.678500,3.355,5.40,mw,38.25,-118.75,210.604025,16.925181,8.482685,12.703933
28210,2004-09-18,23:43:41.490Z,38.023333,-118.658000,0.431,5.35,mw,38.25,-118.75,200.155103,16.562784,8.301056,12.431920
28244,2004-09-28,17:15:24.250Z,35.818167,-120.366000,8.136,5.97,mw,35.75,-120.25,376.189497,21.661740,10.856587,16.259164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37449,2022-10-25,18:42:02.710Z,37.311500,-121.672000,8.380,5.06,mw,37.25,-121.75,149.000137,14.608759,7.321724,10.965241
37482,2022-12-20,10:34:24.770Z,40.525000,-124.423000,17.910,6.40,mw,40.75,-124.25,582.729047,26.093560,13.077759,19.585660
37605,2023-05-11,23:19:41.990Z,40.204167,-121.109500,5.850,5.48,mw,40.25,-121.25,228.468677,17.521583,8.781594,13.151588
37607,2023-05-12,10:18:41.310Z,40.196000,-121.099833,6.060,5.16,mw,40.25,-121.25,164.963046,15.255039,7.645631,11.450335
37695,2023-08-20,21:41:00.970Z,34.408500,-119.188333,4.840,5.08,mw,34.25,-119.25,152.064090,14.735787,7.385388,11.060588

In [6]:
# prompt: convert T_plus to months

# Convert T_plus to months
catalog_data['T_plus_months'] = catalog_data['T_plus'] / 30.44 # Approximate days in a month

In [7]:
# prompt: show all the rows of catalog_data

pd.set_option("display.max_rows", None, "display.max_columns", None)
catalog_data

,date,time,latitude,longitude,depth,mag,magtype,lat_grid,lon_grid,D_eps,T_plus,T_minus,T,T_plus_months
27321,2002-06-17,16:55:07.680Z,40.809833,-124.552000,17.195,5.20,mw,40.75,-124.75,171.817212,15.521487,7.779171,11.650329,0.509904
27743,2003-12-22,19:15:56.240Z,35.700500,-121.100500,8.382,6.50,mw,35.75,-121.25,645.158861,27.247919,13.656309,20.452114,0.895135
28206,2004-09-18,23:02:17.750Z,38.009500,-118.678500,3.355,5.40,mw,38.25,-118.75,210.604025,16.925181,8.482685,12.703933,0.556018
28210,2004-09-18,23:43:41.490Z,38.023333,-118.658000,0.431,5.35,mw,38.25,-118.75,200.155103,16.562784,8.301056,12.431920,0.544112
28244,2004-09-28,17:15:24.250Z,35.818167,-120.366000,8.136,5.97,mw,35.75,-120.25,376.189497,21.661740,10.856587,16.259164,0.711621
28260,2004-09-29,17:10:04.030Z,35.953667,-120.502167,10.772,5.00,mw,35.75,-120.75,140.173742,14.234209,7.134004,10.684106,0.467615
28261,2004-09-29,22:54:54.240Z,35.389833,-118.623500,2.788,5.03,mw,35.25,-118.75,144.519572,14.420268,7.227254,10.823761,0.473728
28485,2005-06-12,15:41:46.520Z,33.532500,-116.566667,13.051,5.20,mw,33.75,-116.75,171.817212,15.521487,7.779171,11.650329,0.509904
28573,2005-09-02,01:27:19.590Z,33.153333,-115.646333,1.207,5.08,mw,33.25,-115.75,152.064090,14.735787,7.385388,11.060588,0.484093
28815,2006-05-24,04:20:26.010Z,32.306667,-115.227833,6.006,5.37,mw,32.25,-115.25,204.270977,16.706802,8.373236,12.540019,0.548844
29045,2007-02-26,12:21:02.140Z,40.642000,-124.870000,4.957,5.40,mh,40.75,-124.75,210.604025,16.925181,8.482685,12.703933,0.556018
29147,2007-06-25,02:32:24.620Z,41.115500,-124.824500,2.563,5.00,mw,41.25,-124.75,140.173742,14.234209,7.134004,10.684106,0.467615
29225,2007-10-31,03:04:54.810Z,37.433500,-121.774333,9.741,5.45,mw,37.25,-121.75,221.598424,17.295508,8.668288,12.981898,0.568184
29278,2008-02-09,07:12:04.550Z,32.359500,-115.277333,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302
29290,2008-02-11,18:29:30.530Z,32.327167,-115.256833,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302
29333,2008-02-19,22:41:29.660Z,32.432500,-115.313000,6.006,5.01,mw,32.25,-115.25,141.607634,14.295960,7.164953,10.730457,0.469644
29343,2008-02-21,14:16:02.821Z,41.144400,-114.872100,7.900,5.90,mw,41.25,-114.75,350.321399,21.015191,10.532545,15.773868,0.690381
29347,2008-02-21,14:34:55.538Z,41.137000,-114.839800,0.000,5.10,ml,41.25,-114.75,155.191048,14.863919,7.449607,11.156763,0.488302
29543,2008-04-26,06:40:10.453Z,39.523100,-119.939300,2.800,5.10,ml,39.75,-119.75,155.191048,14.863919,7.449607,11.156763,0.488302
29652,2008-07-29,18:42:15.670Z,33.948500,-117.766333,15.503,5.44,mw,33.75,-117.75,219.354560,17.220800,8.630845,12.925823,0.565729
29760,2008-12-06,04:18:42.850Z,34.813333,-116.418833,6.370,5.06,mw,34.75,-116.25,149.000137,14.608759,7.321724,10.965241,0.479920
30001,2009-09-19,22:55:17.840Z,32.370667,-115.261167,9.987,5.08,mw,32.25,-115.25,152.064090,14.735787,7.385388,11.060588,0.484093
30010,2009-10-01,10:01:24.670Z,36.387833,-117.858667,3.985,5.00,mw,36.25,-117.75,140.173742,14.234209,7.134004,10.684106,0.467615
30114,2009-12-30,18:48:57.330Z,32.464000,-115.189167,5.971,5.80,mw,32.25,-115.25,316.421997,20.124882,10.086334,15.105608,0.661133
30263,2010-04-04,22:40:42.360Z,32.286167,-115.295333,9.987,7.20,mw,32.25,-115.25,1315.426742,36.892096,18.489848,27.690972,1.211961
30264,2010-04-04,22:43:00.430Z,32.453333,-115.632000,9.981,5.26,ml,32.25,-115.75,182.636118,15.929910,7.983868,11.956889,0.523322
30270,2010-04-04,22:50:17.120Z,32.098667,-115.048167,10.011,5.70,mw,32.25,-115.25,285.802923,19.272290,9.659026,14.465658,0.633124
30278,2010-04-04,23:15:14.240Z,32.300000,-115.259500,9.987,5.43,mw,32.25,-115.25,217.133417,17.146415,8.593564,12.869990,0.563286
30288,2010-04-04,23:25:07.190Z,32.266167,-115.292500,9.987,5.38,mw,32.25,-115.25,206.360545,16.779280,8.409561,12.594421,0.551225
30319,2010-04-05,00:07:07.920Z,31.978833,-115.134167,9.994,5.22,ml,31.75,-115.25,175.350362,15.656451,7.846814,11.751632,0.514338
30883,2010-04-08,16:44:25.010Z,32.164667,-115.268333,9.985,5.29,mw,32.25,-115.25,188.298416,16.138135,8.088227,12.113181,0.530162
31417,2010-06-15,04:26:58.240Z,32.705000,-115.911333,8.756,5.71,mw,32.75,-115.75,288.726514,19.355898,9.700929,14.528414,0.635871
31544,2010-07-07,23:53:33.480Z,33.417333,-116.474667,12.318,5.42,mw,33.25,-116.25,214.934765,17.072351,8.556444,12.814398,0.560853
31957,2011-02-18,17:47:35.770Z,32.047000,-115.062167,14.929,5.09,mw,32.25,-115.25,153.619613,14.799714,7.417428,11.108571,0.486193
32499,2012-08-26,19:31:23.040Z,33.017167,-115.553667,8.323,5.32,mw,33.25,-115.75,194.136264,16.349081,8.193950,12.271515,0.537092
32511,2012-08-26,20:57:58.220Z,33.018500,-115.540333,8.283,5.41,mw,33.25,-115.75,212.758376,16.998607,8.519485,12.759046,0.558430
32591,2012-10-21,06:55:09.510Z,36.309667,-120.856000,8.619,5.29,mw,36.25,-120.75,188.298416,16.138135,8.088227,12.113181,0.530162
32624,2012-12-14,10:36:01.590Z,31.095000,-119.660000,13.000,6.30,mww,31.25,-119.75,526.340352,24.988106,12.523720,18.755913,0.820897
32674,2013-02-13,00:10:14.393Z,38.022200,-118.055300,7.500,5.10,ml,38.25,-118.25,155.191048,14.863919,7.449607,11.156763,0.488302
32765,2013-05-24,03:47:08.180Z,40.191833,-121.059500,7.968,5.69,mw,40.25,-121.25,282.908937,19.189044,9.617304,14.403174,0.630389
33022,2014-03-29,04:09:42.170Z,33.932500,-117.915833,5.090,5.10,mw,33.75,-117.75,155.191048,14.863919,7.449607,11.156763,0.488302
33142,2014-08-24,10:20:44.070Z,38.215167,-122.312333,11.120,6.02,mw,38.25,-122.25,395.828141,22.135704,11.094132,16.614918,0.727191
33411,2015-01-28,21:08:53.710Z,40.317833,-124.606667,16.881,5.72,mw,40.25,-124.75,291.680010,19.439869,9.743014,14.591442,0.638629
33505,2015-05-22,18:47:42.980Z,37.292500,-114.654600,4.000,5.30,ml,37.25,-114.75,190.224594,16.208146,8.123316,12.165731,0.532462
33832,2016-06-10,08:04:38.700Z,33.431500,-116.442667,12.310,5.19,mw,33.25,-116.25,170.077423,15.454442,7.745569,11.600006,0.507702
33882,2016-08-10,02:57:17.510Z,39.329333,-122.801833,14.450,5.09,mw,39.25,-122.75,153.619613,14.799714,7.417428,11.108571,0.486193
33978,2016-12-14,16:41:05.530Z,38.822167,-122.841333,1.480,5.01,mw,38.75,-122.75,141.607634,14.295960,7.164953,10.730457,0.469644
33986,2016-12-28,08:18:00.613Z,38.375500,-118.898900,11.300,5.60,ml,38.25,-118.75,258.146753,18.455819,9.249821,13.852820,0.606302
33987,2016-12-28,08:22:12.208Z,38.390400,-118.897200,12.200,5.60,ml,38.25,-118.75,258.146753,18.455819,9.249821,13.852820,0.606302
33994,2016-12-28,09:13:47.243Z,38.377700,-118.895700,8.800,5.50,ml,38.25,-118.75,233.166775,17.673938,8.857952,13.265945,0.580616
34300,2018-04-05,19:29:16.220Z,33.819833,-119.734000,9.820,5.29,mw,33.75,-119.75,188.298416,16.138135,8.088227,12.113181,0.530162
34598,2019-06-23,03:53:02.890Z,40.273500,-124.300333,9.440,5.58,mw,40.25,-124.25,252.945331,18.296724,9.170084,13.733404,0.601075
34607,2019-07-04,17:33:49.000Z,35.705333,-117.503833,10.500,6.40,mw,35.75,-117.75,582.729047,26.093560,13.077759,19.585660,0.857213
34738,2019-07-05,11:07:53.040Z,35.760333,-117.575000,6.950,5.37,mw,35.75,-117.75,204.270977,16.706802,8.373236,12.540019,0.548844
34757,2019-07-06,03:19:53.040Z,35.769500,-117.599333,8.000,7.10,mw,35.75,-117.75,1188.137400,35.329162,17.706525,26.517843,1.160616
34874,2019-07-06,03:47:53.420Z,35.901167,-117.749500,5.040,5.50,mw,35.75,-117.75,233.166775,17.673938,8.857952,13.265945,0.580616
34978,2019-07-06,04:18:55.790Z,35.910167,-117.684833,7.410,5.44,mw,35.75,-117.75,219.354560,17.220800,8.630845,12.925823,0.565729
35900,2020-03-07,03:52:03.180Z,31.689333,-114.540500,9.980,5.49,mw,31.75,-114.75,230.805773,17.597596,8.819690,13.208643,0.578108
35939,2020-04-11,14:36:37.040Z,38.052500,-118.733333,8.450,5.24,mw,38.25,-118.75,178.956166,15.792589,7.915044,11.853817,0.518810
35989,2020-05-15,11:03:27.176Z,38.168900,-117.849700,2.700,6.50,ml,38.25,-117.75,645.158861,27.247919,13.656309,20.452114,0.895135
35997,2020-05-15,11:26:01.747Z,38.181100,-117.871100,6.800,5.10,ml,38.25,-117.75,155.191048,14.863919,7.449607,11.156763,0.488302
36202,2020-05-20,12:36:53.447Z,38.201200,-117.745300,11.700,5.00,ml,38.25,-117.75,140.173742,14.234209,7.134004,10.684106,0.467615
36229,2020-05-22,00:22:00.588Z,38.230900,-117.793900,7.200,5.10,ml,38.25,-117.75,155.191048,14.863919,7.449607,11.156763,0.488302
36315,2020-06-04,01:32:11.140Z,35.614833,-117.428167,8.440,5.51,mw,35.75,-117.25,235.551930,17.750612,8.896380,13.323496,0.583134
36394,2020-06-24,17:40:49.240Z,36.446833,-117.975167,4.660,5.80,mw,36.25,-117.75,316.421997,20.124882,10.086334,15.105608,0.661133
36417,2020-06-30,09:24:23.549Z,38.153900,-117.958300,8.300,5.00,ml,38.25,-117.75,140.173742,14.234209,7.134004,10.684106,0.467615
36501,2020-08-17,15:30:33.530Z,31.536667,-115.661333,16.220,5.12,mw,31.75,-115.75,158.382308,14.993165,7.514383,11.253774,0.492548
36668,2020-11-13,09:13:51.862Z,38.169300,-117.853300,4.800,5.30,ml,38.25,-117.75,190.224594,16.208146,8.123316,12.165731,0.532462
36701,2020-12-01,23:32:56.573Z,38.163700,-118.083700,5.000,5.10,ml,38.25,-118.25,155.191048,14.863919,7.449607,11.156763,0.488302
36944,2021-06-05,17:55:58.820Z,33.140000,-115.634833,5.780,5.25,mw,33.25,-115.75,180.786779,15.861101,7.949381,11.905241,0.521061
37014,2021-07-08,22:49:48.110Z,38.507500,-119.499833,7.450,6.00,mw,38.75,-119.25,387.852564,21.944886,10.998497,16.471692,0.720923
37015,2021-07-08,22:50:14.370Z,38.512667,-119.502167,7.400,5.03,ml,38.75,-119.75,144.519572,14.420268,7.227254,10.823761,0.473728
37206,2021-12-20,20:10:20.310Z,40.297833,-124.626000,16.510,5.65,ml,40.25,-124.75,271.623078,18.859637,9.452209,14.155923,0.619568
37449,2022-10-25,18:42:02.710Z,37.311500,-121.672000,8.380,5.06,mw,37.25,-121.75,149.000137,14.608759,7.321724,10.965241,0.479920
37482,2022-12-20,10:34:24.770Z,40.525000,-124.423000,17.910,6.40,mw,40.75,-124.25,582.729047,26.093560,13.077759,19.585660,0.857213
37605,2023-05-11,23:19:41.990Z,40.204167,-121.109500,5.850,5.48,mw,40.25,-121.25,228.468677,17.521583,8.781594,13.151588,0.575610
37607,2023-05-12,10:18:41.310Z,40.196000,-121.099833,6.060,5.16,mw,40.25,-121.25,164.963046,15.255039,7.645631,11.450335,0.501151
37695,2023-08-20,21:41:00.970Z,34.408500,-119.188333,4.840,5.08,mw,34.25,-119.25,152.064090,14.735787,7.385388,11.060588,0.484093

In [8]:
# prompt: divide D_eps by 55.5 and add it as another column

catalog_data['D_eps_divided'] = catalog_data['D_eps'] / 55.5

In [9]:
# prompt: round D_eps_divided to integer.

catalog_data['D_eps_divided_rounded'] = catalog_data['D_eps_divided'].round().astype(int)

In [10]:
# prompt: add year_month in the dataframe from date

# Extract year and month from the 'date' column
catalog_data['year'] = catalog_data['date'].dt.year
catalog_data['month'] = catalog_data['date'].dt.month

# Create the 'year_month' column by combining year and month
catalog_data['year_month'] = catalog_data['date'].dt.strftime('%Y-%m')

In [11]:
# prompt: add four columns to catalog_data . 1.) lat_min = lat_grid - 0.5 * D_eps_divided_rounded  , 2.)lat_max =  lat_grid + 0.5 * D_eps_divided_rounded , 3.) lon_min =  lon_grid - 0.5 * D_eps_divided_rounded , 4.) lon_max = lon_grid + 0.5 * D_eps_divided_rounded

# Calculate lat_min, lat_max, lon_min, and lon_max
catalog_data['lat_min'] = catalog_data['lat_grid'] - 0.5 * catalog_data['D_eps_divided_rounded']
catalog_data['lat_max'] = catalog_data['lat_grid'] + 0.5 * catalog_data['D_eps_divided_rounded']
catalog_data['lon_min'] = catalog_data['lon_grid'] - 0.5 * catalog_data['D_eps_divided_rounded']
catalog_data['lon_max'] = catalog_data['lon_grid'] + 0.5 * catalog_data['D_eps_divided_rounded']

In [22]:
# prompt: create two columns lat_range and lon_range in catalog_data with values ranging from lat_min to lat_max and lon_min to lon_max respectively with 0.5 increament.

# Create empty lists to store latitude and longitude ranges
lat_ranges = []
lon_ranges = []

for index, row in catalog_data.iterrows():
    lat_min = row['lat_min']
    lat_max = row['lat_max']
    lon_min = row['lon_min']
    lon_max = row['lon_max']

    # Generate latitude ranges with 0.5 increment
    current_lat = lat_min
    lat_range = []
    while current_lat <= lat_max:
        lat_range.append(current_lat)
        current_lat += 0.5
    lat_ranges.append(lat_range)

    # Generate longitude ranges with 0.5 increment
    current_lon = lon_min
    lon_range = []
    while current_lon <= lon_max:
        lon_range.append(current_lon)
        current_lon += 0.5
    lon_ranges.append(lon_range)

# Add the generated ranges as new columns to the DataFrame
catalog_data['lat_range'] = lat_ranges
catalog_data['lon_range'] = lon_ranges

In [23]:
catalog_data

,date,time,latitude,longitude,depth,mag,magtype,lat_grid,lon_grid,D_eps,T_plus,T_minus,T,T_plus_months,D_eps_divided,D_eps_divided_rounded,year,month,year_month,lat_min,lat_max,lon_min,lon_max,lat_range,lon_range,range,coordinates
27321,2002-06-17,16:55:07.680Z,40.809833,-124.552000,17.195,5.20,mw,40.75,-124.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2002,6,2002-06,39.25,42.25,-126.25,-123.25,"[39.25, 39.75, 40.25, 40.75, 41.25, 41.75, 42.25]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.25, 39.75, 40.25, 40.75, 41....","[(39.25, -126.25), (39.25, -125.75), (39.25, -..."
27743,2003-12-22,19:15:56.240Z,35.700500,-121.100500,8.382,6.50,mw,35.75,-121.25,645.158861,27.247919,13.656309,20.452114,0.895135,11.624484,12,2003,12,2003-12,29.75,41.75,-127.25,-115.25,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -127.25), (29.75, -126.75), (29.75, -..."
28206,2004-09-18,23:02:17.750Z,38.009500,-118.678500,3.355,5.40,mw,38.25,-118.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -..."
28210,2004-09-18,23:43:41.490Z,38.023333,-118.658000,0.431,5.35,mw,38.25,-118.75,200.155103,16.562784,8.301056,12.431920,0.544112,3.606398,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -..."
28244,2004-09-28,17:15:24.250Z,35.818167,-120.366000,8.136,5.97,mw,35.75,-120.25,376.189497,21.661740,10.856587,16.259164,0.711621,6.778189,7,2004,9,2004-09,32.25,39.25,-123.75,-116.75,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -123.75), (32.25, -123.25), (32.25, -..."
28260,2004-09-29,17:10:04.030Z,35.953667,-120.502167,10.772,5.00,mw,35.75,-120.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2004,9,2004-09,34.25,37.25,-122.25,-119.25,"[34.25, 34.75, 35.25, 35.75, 36.25, 36.75, 37.25]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.25, 34.75, 35.25, 35.75, 36....","[(34.25, -122.25), (34.25, -121.75), (34.25, -..."
28261,2004-09-29,22:54:54.240Z,35.389833,-118.623500,2.788,5.03,mw,35.25,-118.75,144.519572,14.420268,7.227254,10.823761,0.473728,2.603956,3,2004,9,2004-09,33.75,36.75,-120.25,-117.25,"[33.75, 34.25, 34.75, 35.25, 35.75, 36.25, 36.75]","[-120.25, -119.75, -119.25, -118.75, -118.25, ...","{'lat_range': [33.75, 34.25, 34.75, 35.25, 35....","[(33.75, -120.25), (33.75, -119.75), (33.75, -..."
28485,2005-06-12,15:41:46.520Z,33.532500,-116.566667,13.051,5.20,mw,33.75,-116.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2005,6,2005-06,32.25,35.25,-118.25,-115.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -118.25), (32.25, -117.75), (32.25, -..."
28573,2005-09-02,01:27:19.590Z,33.153333,-115.646333,1.207,5.08,mw,33.25,-115.75,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2005,9,2005-09,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -..."
28815,2006-05-24,04:20:26.010Z,32.306667,-115.227833,6.006,5.37,mw,32.25,-115.25,204.270977,16.706802,8.373236,12.540019,0.548844,3.680558,4,2006,5,2006-05,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -..."
29045,2007-02-26,12:21:02.140Z,40.642000,-124.870000,4.957,5.40,mh,40.75,-124.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2007,2,2007-02,38.75,42.75,-126.75,-122.75,"[38.75, 39.25, 39.75, 40.25, 40.75, 41.25, 41....","[-126.75, -126.25, -125.75, -125.25, -124.75, ...","{'lat_range': [38.75, 39.25, 39.75, 40.25, 40....","[(38.75, -126.75), (38.75, -126.25), (38.75, -..."
29147,2007-06-25,02:32:24.620Z,41.115500,-124.824500,2.563,5.00,mw,41.25,-124.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2007,6,2007-06,39.75,42.75,-126.25,-123.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -126.25), (39.75, -125.75), (39.75, -..."
29225,2007-10-31,03:04:54.810Z,37.433500,-121.774333,9.741,5.45,mw,37.25,-121.75,221.598424,17.295508,8.668288,12.981898,0.568184,3.992764,4,2007,10,2007-10,35.25,39.25,-123.75,-119.75,"[35.25, 35.75, 36.25, 36.75, 37.25, 37.75, 38....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [35.25, 35.75, 36.25, 36.75, 37....","[(35.25, -123.75), (35.25, -123.25), (35.25, -..."
29278,2008-02-09,07:12:04.550Z,32.359500,-115.277333,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
29290,2008-02-11,18:29:30.530Z,32.327167,-115.256833,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
29333,2008-02-19,22:41:29.660Z,32.432500,-115.313000,6.006,5.01,mw,32.25,-115.25,141.607634,14.295960,7.164953,10.730457,0.469644,2.551489,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
29343,2008-02-21,14:16:02.821Z,41.144400,-114.872100,7.900,5.90,mw,41.25,-114.75,350.321399,21.015191,10.532545,15.773868,0.690381,6.312097,6,2008,2,2008-02,38.25,44.25,-117.75,-111.75,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -117.75), (38.25, -117.25), (38.25, -..."
29347,2008-02-21,14:34:55.538Z,41.137000,-114.839800,0.000,5.10,ml,41.25,-114.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,39.75,42.75,-116.25,-113.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -116.25), (39.75, -115.75), (39.75, -..."
29543,2008-04-26,06:40:10.453Z,39.523100,-119.939300,2.800,5.10,ml,39.75,-119.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,4,2008-04,38.25,41.25,-121.25,-118.25,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41.25]","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -121.25), (38.25, -120.75), (38.25, -..."
29652,2008-07-29,18:42:15.670Z,33.948500,-117.766333,15.503,5.44,mw,33.75,-117.75,219.354560,17.220800,8.630845,12.925823,0.565729,3.952334,4,2008,7,2008-07,31.75,35.75,-119.75,-115.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34....","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -119.75), (31.75, -119.25), (31.75, -..."
29760,2008-12-06,04:18:42.850Z,34.813333,-116.418833,6.370,5.06,mw,34.75,-116.25,149.000137,14.608759,7.321724,10.965241,0.479920,2.684687,3,2008,12,2008-12,33.25,36.25,-117.75,-114.75,"[33.25, 33.75, 34.25, 34.75, 35.25, 35.75, 36.25]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [33.25, 33.75, 34.25, 34.75, 35....","[(33.25, -117.75), (33.25, -117.25), (33.25, -..."
30001,2009-09-19,22:55:17.840Z,32.370667,-115.261167,9.987,5.08,mw,32.25,-115.25,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2009,9,2009-09,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
30010,2009-10-01,10:01:24.670Z,36.387833,-117.858667,3.985,5.00,mw,36.25,-117.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2009,10,2009-10,34.75,37.75,-119.25,-116.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -119.25), (34.75, -118.75), (34.75, -..."
30114,2009-12-30,18:48:57.330Z,32.464000,-115.189167,5.971,5.80,mw,32.25,-115.25,316.421997,20.124882,10.086334,15.105608,0.661133,5.701297,6,2009,12,2009-12,29.25,35.25,-118.25,-112.25,"[29.25, 29.75, 30.25, 30.75, 31.25, 31.75, 32....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [29.25, 29.75, 30.25, 30.75, 31....","[(29.25, -118.25), (29.25, -117.75), (29.25, -..."
30263,2010-04-04,22:40:42.360Z,32.286167,-115.295333,9.987,7.20,mw,32.25,-115.25,1315.426742,36.892096,18.489848,27.690972,1.211961,23.701383,24,2010,4,2010-04,20.25,44.25,-127.25,-103.25,"[20.25, 20.75, 21.25, 21.75, 22.25, 22.75, 23....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [20.25, 20.75, 21.25, 21.75, 22....","[(20.25, -127.25), (20.25, -126.75), (20.25, -..."
30264,2010-04-04,22:43:00.430Z,32.453333,-115.632000,9.981,5.26,ml,32.25,-115.75,182.636118,15.929910,7.983868,11.956889,0.523322,3.290741,3,2010,4,2010-04,30.75,33.75,-117.25,-114.25,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -117.25), (30.75, -116.75), (30.75, -..."
30270,2010-04-04,22:50:17.120Z,32.098667,-115.048167,10.011,5.70,mw,32.25,-115.25,285.802923,19.272290,9.659026,14.465658,0.633124,5.149602,5,2010,4,2010-04,29.75,34.75,-117.75,-112.75,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -117.75), (29.75, -117.25), (29.75, -..."
30278,2010-04-04,23:15:14.240Z,32.300000,-115.259500,9.987,5.43,mw,32.25,-115.25,217.133417,17.146415,8.593564,12.869990,0.563286,3.912314,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -..."
30288,2010-04-04,23:25:07.190Z,32.266167,-115.292500,9.987,5.38,mw,32.25,-115.25,206.360545,16.779280,8.409561,12.594421,0.551225,3.718208,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -..."
30319,2010-04-05,00:07:07.920Z,31.978833,-115.134167,9.994,5.22,ml,31.75,-115.25,175.350362,15.656451,7.846814,11.751632,0.514338,3.159466,3,2010,4,2010-04,30.25,33.25,-116.75,-113.75,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33.25]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -116.75), (30.25, -116.25), (30.25, -..."
30883,2010-04-08,16:44:25.010Z,32.164667,-115.268333,9.985,5.29,mw,32.25,-115.25,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2010,4,2010-04,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
31417,2010-06-15,04:26:58.240Z,32.705000,-115.911333,8.756,5.71,mw,32.75,-115.75,288.726514,19.355898,9.700929,14.528414,0.635871,5.202280,5,2010,6,2010-06,30.25,35.25,-118.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -118.25), (30.25, -117.75), (30.25, -..."
31544,2010-07-07,23:53:33.480Z,33.417333,-116.474667,12.318,5.42,mw,33.25,-116.25,214.934765,17.072351,8.556444,12.814398,0.560853,3.872698,4,2010,7,2010-07,31.25,35.25,-118.25,-114.25,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -118.25), (31.25, -117.75), (31.25, -..."
31957,2011-02-18,17:47:35.770Z,32.047000,-115.062167,14.929,5.09,mw,32.25,-115.25,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2011,2,2011-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
32499,2012-08-26,19:31:23.040Z,33.017167,-115.553667,8.323,5.32,mw,33.25,-115.75,194.136264,16.349081,8.193950,12.271515,0.537092,3.497951,3,2012,8,2012-08,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -..."
32511,2012-08-26,20:57:58.220Z,33.018500,-115.540333,8.283,5.41,mw,33.25,-115.75,212.758376,16.998607,8.519485,12.759046,0.558430,3.833484,4,2012,8,2012-08,31.25,35.25,-117.75,-113.75,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -117.75), (31.25, -117.25), (31.25, -..."
32591,2012-10-21,06:55:09.510Z,36.309667,-120.856000,8.619,5.29,mw,36.25,-120.75,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2012,10,2012-10,34.75,37.75,-122.25,-119.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -122.25), (34.75, -121.75), (34.75, -..."
32624,2012-12-14,10:36:01.590Z,31.095000,-119.660000,13.000,6.30,mww,31.25,-119.75,526.340352,24.988106,12.523720,18.755913,0.820897,9.483610,9,2012,12,2012-12,26.75,35.75,-124.25,-115.25,"[26.75, 27.25, 27.75, 28.25, 28.75, 29.25, 29....","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [26.75, 27.25, 27.75, 28.25, 28....","[(26.75, -124.25), (26.75, -123.75), (26.75, -..."
32674,2013-02-13,00:10:14.393Z,38.022200,-118.055300,7.500,5.10,ml,38.25,-118.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2013,2,2013-02,36.75,39.75,-119.75,-116.75,"[36.75, 37.25, 37.75, 38.25, 38.75, 39.25, 39.75]","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [36.75, 37.25, 37.75, 38.25, 38....","[(36.75, -119.75), (36.75, -119.25), (36.75, -..."
32765,2013-05-24,03:47:08.180Z,40.191833,-121.059500,7.968,5.69,mw,40.25,-121.25,282.908937,19.189044,9.617304,14.403174,0.630389,5.097458,5,2013,5,2013-05,37.75,42.75,-123.75,-118.75,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -123.75), (37.75, -123.25), (37.75, -..."
33022,2014-03-29,04:09:42.170Z,33.932500,-117.915833,5.090,5.10,mw,33.75,-117.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2014,3,2014-03,32.25,35.25,-119.25,-116.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -119.25), (32.25, -118.75), (32.25, -..."
33142,2014-08-24,10:20:44.070Z,38.215167,-122.312333,11.120,6.02,mw,38.25,-122.25,395.828141,22.135704,11.094132,16.614918,0.727191,7.132039,7,2014,8,2014-08,34.75,41.75,-125.75,-118.75,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37....","[-125.75, -125.25, -124.75, -124.25, -123.75, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -125.75), (34.75, -125.25), (34.75, -..."
33411,2015-01-28,21:08:53.710Z,40.317833,-124.606667,16.881,5.72,mw,40.25,-124.75,291.680010,19.439869,9.743014,14.591442,0.638629,5.255496,5,2015,1,2015-01,37.75,42.75,-127.25,-122.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -127.25), (37.75, -126.75), (37.75, -..."
33505,2015-05-22,18:47:42.980Z,37.292500,-114.654600,4.000,5.30,ml,37.25,-114.75,190.224594,16.208146,8.123316,12.165731,0.532462,3.427470,3,2015,5,2015-05,35.75,38.75,-116.25,-113.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -116.25), (35.75, -115.75), (35.75, -..."
33832,2016-06-10,08:04:38.700Z,33.431500,-116.442667,12.310,5.19,mw,33.25,-116.25,170.077423,15.454442,7.745569,11.600006,0.507702,3.064458,3,2016,6,2016-06,31.75,34.75,-117.75,-114.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.75), (31.75, -117.25), (31.75, -..."
33882,2016-08-10,02:57:17.510Z,39.329333,-122.801833,14.450,5.09,mw,39.25,-122.75,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2016,8,2016-08,37.75,40.75,-124.25,-121.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40.75]","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -124.25), (37.75, -123.75), (37.75, -..."
33978,2016-12-14,16:41:05.530Z,38.822167,-122.841333,1.480,5.01,mw,38.75,-122.75,141.607634,14.295960,7.164953,10.730457,0.469644,2.551489,3,2016,12,2016-12,37.25,40.25,-124.25,-121.25,"[37.25, 37.75, 38.25, 38.75, 39.25, 39.75, 40.25]","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [37.25, 37.75, 38.25, 38.75, 39....","[(37.25, -124.25), (37.25, -123.75), (37.25, -..."
33986,2016-12-28,08:18:00.613Z,38.375500,-118.898900,11.300,5.60,ml,38.25,-118.75,258.146753,18.455819,9.249821,13.852820,0.606302,4.651293,5,2016,12,2016-12,35.75,40.75,-121.25,-116.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38....","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -121.25), (35.75, -120.75), (35.75, -..."
33987,2016-12-28,08:22:12.208Z,38.390400,-118.897200,12.200,5.60,ml,38.25,-118.75,258.146753,18.455819,9.249821,13.852820,0.606302,4.651293,5,2016,12,2016-12,35.75,40.75,-121.25,-116.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38....","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -121.25), (35.75, -120.75), (35.75, -..."
33994,2016-12-28,09:13:47.243Z,38.377700,-118.895700,8.800,5.50,ml,38.25,-118.75,233.166775,17.673938,8.857952,13.265945,0.580616,4.201203,4,2016,12,2016-12,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -..."

In [24]:
# prompt: create a column such that I get a list of coordinates using each value of lat_range for every value of lon_range

from itertools import product

# Create an empty list to store the coordinates
coordinates_list = []

# Iterate through each row of the DataFrame
for index, row in catalog_data.iterrows():
    lat_range = row['lat_range']
    lon_range = row['lon_range']

    # Use itertools.product to generate all possible coordinate pairs
    coordinates = list(product(lat_range, lon_range))
    coordinates_list.append(coordinates)

# Add the list of coordinates as a new column to the DataFrame
catalog_data['coordinates'] = coordinates_list
catalog_data

,date,time,latitude,longitude,depth,mag,magtype,lat_grid,lon_grid,D_eps,T_plus,T_minus,T,T_plus_months,D_eps_divided,D_eps_divided_rounded,year,month,year_month,lat_min,lat_max,lon_min,lon_max,lat_range,lon_range,range,coordinates
27321,2002-06-17,16:55:07.680Z,40.809833,-124.552000,17.195,5.20,mw,40.75,-124.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2002,6,2002-06,39.25,42.25,-126.25,-123.25,"[39.25, 39.75, 40.25, 40.75, 41.25, 41.75, 42.25]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.25, 39.75, 40.25, 40.75, 41....","[(39.25, -126.25), (39.25, -125.75), (39.25, -..."
27743,2003-12-22,19:15:56.240Z,35.700500,-121.100500,8.382,6.50,mw,35.75,-121.25,645.158861,27.247919,13.656309,20.452114,0.895135,11.624484,12,2003,12,2003-12,29.75,41.75,-127.25,-115.25,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -127.25), (29.75, -126.75), (29.75, -..."
28206,2004-09-18,23:02:17.750Z,38.009500,-118.678500,3.355,5.40,mw,38.25,-118.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -..."
28210,2004-09-18,23:43:41.490Z,38.023333,-118.658000,0.431,5.35,mw,38.25,-118.75,200.155103,16.562784,8.301056,12.431920,0.544112,3.606398,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -..."
28244,2004-09-28,17:15:24.250Z,35.818167,-120.366000,8.136,5.97,mw,35.75,-120.25,376.189497,21.661740,10.856587,16.259164,0.711621,6.778189,7,2004,9,2004-09,32.25,39.25,-123.75,-116.75,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -123.75), (32.25, -123.25), (32.25, -..."
28260,2004-09-29,17:10:04.030Z,35.953667,-120.502167,10.772,5.00,mw,35.75,-120.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2004,9,2004-09,34.25,37.25,-122.25,-119.25,"[34.25, 34.75, 35.25, 35.75, 36.25, 36.75, 37.25]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.25, 34.75, 35.25, 35.75, 36....","[(34.25, -122.25), (34.25, -121.75), (34.25, -..."
28261,2004-09-29,22:54:54.240Z,35.389833,-118.623500,2.788,5.03,mw,35.25,-118.75,144.519572,14.420268,7.227254,10.823761,0.473728,2.603956,3,2004,9,2004-09,33.75,36.75,-120.25,-117.25,"[33.75, 34.25, 34.75, 35.25, 35.75, 36.25, 36.75]","[-120.25, -119.75, -119.25, -118.75, -118.25, ...","{'lat_range': [33.75, 34.25, 34.75, 35.25, 35....","[(33.75, -120.25), (33.75, -119.75), (33.75, -..."
28485,2005-06-12,15:41:46.520Z,33.532500,-116.566667,13.051,5.20,mw,33.75,-116.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2005,6,2005-06,32.25,35.25,-118.25,-115.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -118.25), (32.25, -117.75), (32.25, -..."
28573,2005-09-02,01:27:19.590Z,33.153333,-115.646333,1.207,5.08,mw,33.25,-115.75,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2005,9,2005-09,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -..."
28815,2006-05-24,04:20:26.010Z,32.306667,-115.227833,6.006,5.37,mw,32.25,-115.25,204.270977,16.706802,8.373236,12.540019,0.548844,3.680558,4,2006,5,2006-05,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -..."
29045,2007-02-26,12:21:02.140Z,40.642000,-124.870000,4.957,5.40,mh,40.75,-124.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2007,2,2007-02,38.75,42.75,-126.75,-122.75,"[38.75, 39.25, 39.75, 40.25, 40.75, 41.25, 41....","[-126.75, -126.25, -125.75, -125.25, -124.75, ...","{'lat_range': [38.75, 39.25, 39.75, 40.25, 40....","[(38.75, -126.75), (38.75, -126.25), (38.75, -..."
29147,2007-06-25,02:32:24.620Z,41.115500,-124.824500,2.563,5.00,mw,41.25,-124.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2007,6,2007-06,39.75,42.75,-126.25,-123.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -126.25), (39.75, -125.75), (39.75, -..."
29225,2007-10-31,03:04:54.810Z,37.433500,-121.774333,9.741,5.45,mw,37.25,-121.75,221.598424,17.295508,8.668288,12.981898,0.568184,3.992764,4,2007,10,2007-10,35.25,39.25,-123.75,-119.75,"[35.25, 35.75, 36.25, 36.75, 37.25, 37.75, 38....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [35.25, 35.75, 36.25, 36.75, 37....","[(35.25, -123.75), (35.25, -123.25), (35.25, -..."
29278,2008-02-09,07:12:04.550Z,32.359500,-115.277333,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
29290,2008-02-11,18:29:30.530Z,32.327167,-115.256833,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
29333,2008-02-19,22:41:29.660Z,32.432500,-115.313000,6.006,5.01,mw,32.25,-115.25,141.607634,14.295960,7.164953,10.730457,0.469644,2.551489,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
29343,2008-02-21,14:16:02.821Z,41.144400,-114.872100,7.900,5.90,mw,41.25,-114.75,350.321399,21.015191,10.532545,15.773868,0.690381,6.312097,6,2008,2,2008-02,38.25,44.25,-117.75,-111.75,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -117.75), (38.25, -117.25), (38.25, -..."
29347,2008-02-21,14:34:55.538Z,41.137000,-114.839800,0.000,5.10,ml,41.25,-114.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,39.75,42.75,-116.25,-113.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -116.25), (39.75, -115.75), (39.75, -..."
29543,2008-04-26,06:40:10.453Z,39.523100,-119.939300,2.800,5.10,ml,39.75,-119.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,4,2008-04,38.25,41.25,-121.25,-118.25,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41.25]","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -121.25), (38.25, -120.75), (38.25, -..."
29652,2008-07-29,18:42:15.670Z,33.948500,-117.766333,15.503,5.44,mw,33.75,-117.75,219.354560,17.220800,8.630845,12.925823,0.565729,3.952334,4,2008,7,2008-07,31.75,35.75,-119.75,-115.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34....","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -119.75), (31.75, -119.25), (31.75, -..."
29760,2008-12-06,04:18:42.850Z,34.813333,-116.418833,6.370,5.06,mw,34.75,-116.25,149.000137,14.608759,7.321724,10.965241,0.479920,2.684687,3,2008,12,2008-12,33.25,36.25,-117.75,-114.75,"[33.25, 33.75, 34.25, 34.75, 35.25, 35.75, 36.25]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [33.25, 33.75, 34.25, 34.75, 35....","[(33.25, -117.75), (33.25, -117.25), (33.25, -..."
30001,2009-09-19,22:55:17.840Z,32.370667,-115.261167,9.987,5.08,mw,32.25,-115.25,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2009,9,2009-09,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
30010,2009-10-01,10:01:24.670Z,36.387833,-117.858667,3.985,5.00,mw,36.25,-117.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2009,10,2009-10,34.75,37.75,-119.25,-116.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -119.25), (34.75, -118.75), (34.75, -..."
30114,2009-12-30,18:48:57.330Z,32.464000,-115.189167,5.971,5.80,mw,32.25,-115.25,316.421997,20.124882,10.086334,15.105608,0.661133,5.701297,6,2009,12,2009-12,29.25,35.25,-118.25,-112.25,"[29.25, 29.75, 30.25, 30.75, 31.25, 31.75, 32....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [29.25, 29.75, 30.25, 30.75, 31....","[(29.25, -118.25), (29.25, -117.75), (29.25, -..."
30263,2010-04-04,22:40:42.360Z,32.286167,-115.295333,9.987,7.20,mw,32.25,-115.25,1315.426742,36.892096,18.489848,27.690972,1.211961,23.701383,24,2010,4,2010-04,20.25,44.25,-127.25,-103.25,"[20.25, 20.75, 21.25, 21.75, 22.25, 22.75, 23....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [20.25, 20.75, 21.25, 21.75, 22....","[(20.25, -127.25), (20.25, -126.75), (20.25, -..."
30264,2010-04-04,22:43:00.430Z,32.453333,-115.632000,9.981,5.26,ml,32.25,-115.75,182.636118,15.929910,7.983868,11.956889,0.523322,3.290741,3,2010,4,2010-04,30.75,33.75,-117.25,-114.25,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -117.25), (30.75, -116.75), (30.75, -..."
30270,2010-04-04,22:50:17.120Z,32.098667,-115.048167,10.011,5.70,mw,32.25,-115.25,285.802923,19.272290,9.659026,14.465658,0.633124,5.149602,5,2010,4,2010-04,29.75,34.75,-117.75,-112.75,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -117.75), (29.75, -117.25), (29.75, -..."
30278,2010-04-04,23:15:14.240Z,32.300000,-115.259500,9.987,5.43,mw,32.25,-115.25,217.133417,17.146415,8.593564,12.869990,0.563286,3.912314,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -..."
30288,2010-04-04,23:25:07.190Z,32.266167,-115.292500,9.987,5.38,mw,32.25,-115.25,206.360545,16.779280,8.409561,12.594421,0.551225,3.718208,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -..."
30319,2010-04-05,00:07:07.920Z,31.978833,-115.134167,9.994,5.22,ml,31.75,-115.25,175.350362,15.656451,7.846814,11.751632,0.514338,3.159466,3,2010,4,2010-04,30.25,33.25,-116.75,-113.75,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33.25]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -116.75), (30.25, -116.25), (30.25, -..."
30883,2010-04-08,16:44:25.010Z,32.164667,-115.268333,9.985,5.29,mw,32.25,-115.25,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2010,4,2010-04,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
31417,2010-06-15,04:26:58.240Z,32.705000,-115.911333,8.756,5.71,mw,32.75,-115.75,288.726514,19.355898,9.700929,14.528414,0.635871,5.202280,5,2010,6,2010-06,30.25,35.25,-118.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -118.25), (30.25, -117.75), (30.25, -..."
31544,2010-07-07,23:53:33.480Z,33.417333,-116.474667,12.318,5.42,mw,33.25,-116.25,214.934765,17.072351,8.556444,12.814398,0.560853,3.872698,4,2010,7,2010-07,31.25,35.25,-118.25,-114.25,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -118.25), (31.25, -117.75), (31.25, -..."
31957,2011-02-18,17:47:35.770Z,32.047000,-115.062167,14.929,5.09,mw,32.25,-115.25,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2011,2,2011-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -..."
32499,2012-08-26,19:31:23.040Z,33.017167,-115.553667,8.323,5.32,mw,33.25,-115.75,194.136264,16.349081,8.193950,12.271515,0.537092,3.497951,3,2012,8,2012-08,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -..."
32511,2012-08-26,20:57:58.220Z,33.018500,-115.540333,8.283,5.41,mw,33.25,-115.75,212.758376,16.998607,8.519485,12.759046,0.558430,3.833484,4,2012,8,2012-08,31.25,35.25,-117.75,-113.75,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -117.75), (31.25, -117.25), (31.25, -..."
32591,2012-10-21,06:55:09.510Z,36.309667,-120.856000,8.619,5.29,mw,36.25,-120.75,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2012,10,2012-10,34.75,37.75,-122.25,-119.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -122.25), (34.75, -121.75), (34.75, -..."
32624,2012-12-14,10:36:01.590Z,31.095000,-119.660000,13.000,6.30,mww,31.25,-119.75,526.340352,24.988106,12.523720,18.755913,0.820897,9.483610,9,2012,12,2012-12,26.75,35.75,-124.25,-115.25,"[26.75, 27.25, 27.75, 28.25, 28.75, 29.25, 29....","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [26.75, 27.25, 27.75, 28.25, 28....","[(26.75, -124.25), (26.75, -123.75), (26.75, -..."
32674,2013-02-13,00:10:14.393Z,38.022200,-118.055300,7.500,5.10,ml,38.25,-118.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2013,2,2013-02,36.75,39.75,-119.75,-116.75,"[36.75, 37.25, 37.75, 38.25, 38.75, 39.25, 39.75]","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [36.75, 37.25, 37.75, 38.25, 38....","[(36.75, -119.75), (36.75, -119.25), (36.75, -..."
32765,2013-05-24,03:47:08.180Z,40.191833,-121.059500,7.968,5.69,mw,40.25,-121.25,282.908937,19.189044,9.617304,14.403174,0.630389,5.097458,5,2013,5,2013-05,37.75,42.75,-123.75,-118.75,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -123.75), (37.75, -123.25), (37.75, -..."
33022,2014-03-29,04:09:42.170Z,33.932500,-117.915833,5.090,5.10,mw,33.75,-117.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2014,3,2014-03,32.25,35.25,-119.25,-116.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -119.25), (32.25, -118.75), (32.25, -..."
33142,2014-08-24,10:20:44.070Z,38.215167,-122.312333,11.120,6.02,mw,38.25,-122.25,395.828141,22.135704,11.094132,16.614918,0.727191,7.132039,7,2014,8,2014-08,34.75,41.75,-125.75,-118.75,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37....","[-125.75, -125.25, -124.75, -124.25, -123.75, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -125.75), (34.75, -125.25), (34.75, -..."
33411,2015-01-28,21:08:53.710Z,40.317833,-124.606667,16.881,5.72,mw,40.25,-124.75,291.680010,19.439869,9.743014,14.591442,0.638629,5.255496,5,2015,1,2015-01,37.75,42.75,-127.25,-122.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -127.25), (37.75, -126.75), (37.75, -..."
33505,2015-05-22,18:47:42.980Z,37.292500,-114.654600,4.000,5.30,ml,37.25,-114.75,190.224594,16.208146,8.123316,12.165731,0.532462,3.427470,3,2015,5,2015-05,35.75,38.75,-116.25,-113.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -116.25), (35.75, -115.75), (35.75, -..."
33832,2016-06-10,08:04:38.700Z,33.431500,-116.442667,12.310,5.19,mw,33.25,-116.25,170.077423,15.454442,7.745569,11.600006,0.507702,3.064458,3,2016,6,2016-06,31.75,34.75,-117.75,-114.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.75), (31.75, -117.25), (31.75, -..."
33882,2016-08-10,02:57:17.510Z,39.329333,-122.801833,14.450,5.09,mw,39.25,-122.75,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2016,8,2016-08,37.75,40.75,-124.25,-121.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40.75]","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -124.25), (37.75, -123.75), (37.75, -..."
33978,2016-12-14,16:41:05.530Z,38.822167,-122.841333,1.480,5.01,mw,38.75,-122.75,141.607634,14.295960,7.164953,10.730457,0.469644,2.551489,3,2016,12,2016-12,37.25,40.25,-124.25,-121.25,"[37.25, 37.75, 38.25, 38.75, 39.25, 39.75, 40.25]","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [37.25, 37.75, 38.25, 38.75, 39....","[(37.25, -124.25), (37.25, -123.75), (37.25, -..."
33986,2016-12-28,08:18:00.613Z,38.375500,-118.898900,11.300,5.60,ml,38.25,-118.75,258.146753,18.455819,9.249821,13.852820,0.606302,4.651293,5,2016,12,2016-12,35.75,40.75,-121.25,-116.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38....","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -121.25), (35.75, -120.75), (35.75, -..."
33987,2016-12-28,08:22:12.208Z,38.390400,-118.897200,12.200,5.60,ml,38.25,-118.75,258.146753,18.455819,9.249821,13.852820,0.606302,4.651293,5,2016,12,2016-12,35.75,40.75,-121.25,-116.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38....","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -121.25), (35.75, -120.75), (35.75, -..."
33994,2016-12-28,09:13:47.243Z,38.377700,-118.895700,8.800,5.50,ml,38.25,-118.75,233.166775,17.673938,8.857952,13.265945,0.580616,4.201203,4,2016,12,2016-12,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -..."

In [27]:
# prompt: create a new column anamoly_time which has values same as year_month if T_plus_months < 1 and decrement 1 month from year_month if T_plus_months > 1

import pandas as pd

# Assuming 'catalog_data' DataFrame is already defined as in the provided code

# Create the 'anomaly_time' column based on the conditions
catalog_data['anomaly_time'] = pd.to_datetime(catalog_data['year_month'])

# Apply the conditions
catalog_data.loc[catalog_data['T_plus_months'] < 1, 'anomaly_time'] = pd.to_datetime(catalog_data['year_month'])
catalog_data.loc[catalog_data['T_plus_months'] > 1, 'anomaly_time'] = pd.to_datetime(catalog_data['year_month']) - pd.DateOffset(months=1)

# Display the updated DataFrame
catalog_data

,date,time,latitude,longitude,depth,mag,magtype,lat_grid,lon_grid,D_eps,T_plus,T_minus,T,T_plus_months,D_eps_divided,D_eps_divided_rounded,year,month,year_month,lat_min,lat_max,lon_min,lon_max,lat_range,lon_range,range,coordinates,time_period,anomaly_time
27321,2002-06-17,16:55:07.680Z,40.809833,-124.552000,17.195,5.20,mw,40.75,-124.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2002,6,2002-06,39.25,42.25,-126.25,-123.25,"[39.25, 39.75, 40.25, 40.75, 41.25, 41.75, 42.25]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.25, 39.75, 40.25, 40.75, 41....","[(39.25, -126.25), (39.25, -125.75), (39.25, -...",[2002-06],2002-06-01
27743,2003-12-22,19:15:56.240Z,35.700500,-121.100500,8.382,6.50,mw,35.75,-121.25,645.158861,27.247919,13.656309,20.452114,0.895135,11.624484,12,2003,12,2003-12,29.75,41.75,-127.25,-115.25,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -127.25), (29.75, -126.75), (29.75, -...",[2003-12],2003-12-01
28206,2004-09-18,23:02:17.750Z,38.009500,-118.678500,3.355,5.40,mw,38.25,-118.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -...",[2004-09],2004-09-01
28210,2004-09-18,23:43:41.490Z,38.023333,-118.658000,0.431,5.35,mw,38.25,-118.75,200.155103,16.562784,8.301056,12.431920,0.544112,3.606398,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -...",[2004-09],2004-09-01
28244,2004-09-28,17:15:24.250Z,35.818167,-120.366000,8.136,5.97,mw,35.75,-120.25,376.189497,21.661740,10.856587,16.259164,0.711621,6.778189,7,2004,9,2004-09,32.25,39.25,-123.75,-116.75,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -123.75), (32.25, -123.25), (32.25, -...",[2004-09],2004-09-01
28260,2004-09-29,17:10:04.030Z,35.953667,-120.502167,10.772,5.00,mw,35.75,-120.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2004,9,2004-09,34.25,37.25,-122.25,-119.25,"[34.25, 34.75, 35.25, 35.75, 36.25, 36.75, 37.25]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.25, 34.75, 35.25, 35.75, 36....","[(34.25, -122.25), (34.25, -121.75), (34.25, -...",[2004-09],2004-09-01
28261,2004-09-29,22:54:54.240Z,35.389833,-118.623500,2.788,5.03,mw,35.25,-118.75,144.519572,14.420268,7.227254,10.823761,0.473728,2.603956,3,2004,9,2004-09,33.75,36.75,-120.25,-117.25,"[33.75, 34.25, 34.75, 35.25, 35.75, 36.25, 36.75]","[-120.25, -119.75, -119.25, -118.75, -118.25, ...","{'lat_range': [33.75, 34.25, 34.75, 35.25, 35....","[(33.75, -120.25), (33.75, -119.75), (33.75, -...",[2004-09],2004-09-01
28485,2005-06-12,15:41:46.520Z,33.532500,-116.566667,13.051,5.20,mw,33.75,-116.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2005,6,2005-06,32.25,35.25,-118.25,-115.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -118.25), (32.25, -117.75), (32.25, -...",[2005-06],2005-06-01
28573,2005-09-02,01:27:19.590Z,33.153333,-115.646333,1.207,5.08,mw,33.25,-115.75,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2005,9,2005-09,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -...",[2005-09],2005-09-01
28815,2006-05-24,04:20:26.010Z,32.306667,-115.227833,6.006,5.37,mw,32.25,-115.25,204.270977,16.706802,8.373236,12.540019,0.548844,3.680558,4,2006,5,2006-05,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -...",[2006-05],2006-05-01
29045,2007-02-26,12:21:02.140Z,40.642000,-124.870000,4.957,5.40,mh,40.75,-124.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2007,2,2007-02,38.75,42.75,-126.75,-122.75,"[38.75, 39.25, 39.75, 40.25, 40.75, 41.25, 41....","[-126.75, -126.25, -125.75, -125.25, -124.75, ...","{'lat_range': [38.75, 39.25, 39.75, 40.25, 40....","[(38.75, -126.75), (38.75, -126.25), (38.75, -...",[2007-02],2007-02-01
29147,2007-06-25,02:32:24.620Z,41.115500,-124.824500,2.563,5.00,mw,41.25,-124.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2007,6,2007-06,39.75,42.75,-126.25,-123.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -126.25), (39.75, -125.75), (39.75, -...",[2007-06],2007-06-01
29225,2007-10-31,03:04:54.810Z,37.433500,-121.774333,9.741,5.45,mw,37.25,-121.75,221.598424,17.295508,8.668288,12.981898,0.568184,3.992764,4,2007,10,2007-10,35.25,39.25,-123.75,-119.75,"[35.25, 35.75, 36.25, 36.75, 37.25, 37.75, 38....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [35.25, 35.75, 36.25, 36.75, 37....","[(35.25, -123.75), (35.25, -123.25), (35.25, -...",[2007-10],2007-10-01
29278,2008-02-09,07:12:04.550Z,32.359500,-115.277333,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2008-02],2008-02-01
29290,2008-02-11,18:29:30.530Z,32.327167,-115.256833,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2008-02],2008-02-01
29333,2008-02-19,22:41:29.660Z,32.432500,-115.313000,6.006,5.01,mw,32.25,-115.25,141.607634,14.295960,7.164953,10.730457,0.469644,2.551489,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2008-02],2008-02-01
29343,2008-02-21,14:16:02.821Z,41.144400,-114.872100,7.900,5.90,mw,41.25,-114.75,350.321399,21.015191,10.532545,15.773868,0.690381,6.312097,6,2008,2,2008-02,38.25,44.25,-117.75,-111.75,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -117.75), (38.25, -117.25), (38.25, -...",[2008-02],2008-02-01
29347,2008-02-21,14:34:55.538Z,41.137000,-114.839800,0.000,5.10,ml,41.25,-114.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,39.75,42.75,-116.25,-113.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -116.25), (39.75, -115.75), (39.75, -...",[2008-02],2008-02-01
29543,2008-04-26,06:40:10.453Z,39.523100,-119.939300,2.800,5.10,ml,39.75,-119.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,4,2008-04,38.25,41.25,-121.25,-118.25,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41.25]","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -121.25), (38.25, -120.75), (38.25, -...",[2008-04],2008-04-01
29652,2008-07-29,18:42:15.670Z,33.948500,-117.766333,15.503,5.44,mw,33.75,-117.75,219.354560,17.220800,8.630845,12.925823,0.565729,3.952334,4,2008,7,2008-07,31.75,35.75,-119.75,-115.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34....","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -119.75), (31.75, -119.25), (31.75, -...",[2008-07],2008-07-01
29760,2008-12-06,04:18:42.850Z,34.813333,-116.418833,6.370,5.06,mw,34.75,-116.25,149.000137,14.608759,7.321724,10.965241,0.479920,2.684687,3,2008,12,2008-12,33.25,36.25,-117.75,-114.75,"[33.25, 33.75, 34.25, 34.75, 35.25, 35.75, 36.25]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [33.25, 33.75, 34.25, 34.75, 35....","[(33.25, -117.75), (33.25, -117.25), (33.25, -...",[2008-12],2008-12-01
30001,2009-09-19,22:55:17.840Z,32.370667,-115.261167,9.987,5.08,mw,32.25,-115.25,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2009,9,2009-09,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2009-09],2009-09-01
30010,2009-10-01,10:01:24.670Z,36.387833,-117.858667,3.985,5.00,mw,36.25,-117.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2009,10,2009-10,34.75,37.75,-119.25,-116.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -119.25), (34.75, -118.75), (34.75, -...",[2009-10],2009-10-01
30114,2009-12-30,18:48:57.330Z,32.464000,-115.189167,5.971,5.80,mw,32.25,-115.25,316.421997,20.124882,10.086334,15.105608,0.661133,5.701297,6,2009,12,2009-12,29.25,35.25,-118.25,-112.25,"[29.25, 29.75, 30.25, 30.75, 31.25, 31.75, 32....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [29.25, 29.75, 30.25, 30.75, 31....","[(29.25, -118.25), (29.25, -117.75), (29.25, -...",[2009-12],2009-12-01
30263,2010-04-04,22:40:42.360Z,32.286167,-115.295333,9.987,7.20,mw,32.25,-115.25,1315.426742,36.892096,18.489848,27.690972,1.211961,23.701383,24,2010,4,2010-04,20.25,44.25,-127.25,-103.25,"[20.25, 20.75, 21.25, 21.75, 22.25, 22.75, 23....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [20.25, 20.75, 21.25, 21.75, 22....","[(20.25, -127.25), (20.25, -126.75), (20.25, -...",[2010-04],2010-03-01
30264,2010-04-04,22:43:00.430Z,32.453333,-115.632000,9.981,5.26,ml,32.25,-115.75,182.636118,15.929910,7.983868,11.956889,0.523322,3.290741,3,2010,4,2010-04,30.75,33.75,-117.25,-114.25,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -117.25), (30.75, -116.75), (30.75, -...",[2010-04],2010-04-01
30270,2010-04-04,22:50:17.120Z,32.098667,-115.048167,10.011,5.70,mw,32.25,-115.25,285.802923,19.272290,9.659026,14.465658,0.633124,5.149602,5,2010,4,2010-04,29.75,34.75,-117.75,-112.75,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -117.75), (29.75, -117.25), (29.75, -...",[2010-04],2010-04-01
30278,2010-04-04,23:15:14.240Z,32.300000,-115.259500,9.987,5.43,mw,32.25,-115.25,217.133417,17.146415,8.593564,12.869990,0.563286,3.912314,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -...",[2010-04],2010-04-01
30288,2010-04-04,23:25:07.190Z,32.266167,-115.292500,9.987,5.38,mw,32.25,-115.25,206.360545,16.779280,8.409561,12.594421,0.551225,3.718208,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -...",[2010-04],2010-04-01
30319,2010-04-05,00:07:07.920Z,31.978833,-115.134167,9.994,5.22,ml,31.75,-115.25,175.350362,15.656451,7.846814,11.751632,0.514338,3.159466,3,2010,4,2010-04,30.25,33.25,-116.75,-113.75,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33.25]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -116.75), (30.25, -116.25), (30.25, -...",[2010-04],2010-04-01
30883,2010-04-08,16:44:25.010Z,32.164667,-115.268333,9.985,5.29,mw,32.25,-115.25,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2010,4,2010-04,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2010-04],2010-04-01
31417,2010-06-15,04:26:58.240Z,32.705000,-115.911333,8.756,5.71,mw,32.75,-115.75,288.726514,19.355898,9.700929,14.528414,0.635871,5.202280,5,2010,6,2010-06,30.25,35.25,-118.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -118.25), (30.25, -117.75), (30.25, -...",[2010-06],2010-06-01
31544,2010-07-07,23:53:33.480Z,33.417333,-116.474667,12.318,5.42,mw,33.25,-116.25,214.934765,17.072351,8.556444,12.814398,0.560853,3.872698,4,2010,7,2010-07,31.25,35.25,-118.25,-114.25,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -118.25), (31.25, -117.75), (31.25, -...",[2010-07],2010-07-01
31957,2011-02-18,17:47:35.770Z,32.047000,-115.062167,14.929,5.09,mw,32.25,-115.25,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2011,2,2011-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2011-02],2011-02-01
32499,2012-08-26,19:31:23.040Z,33.017167,-115.553667,8.323,5.32,mw,33.25,-115.75,194.136264,16.349081,8.193950,12.271515,0.537092,3.497951,3,2012,8,2012-08,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -...",[2012-08],2012-08-01
32511,2012-08-26,20:57:58.220Z,33.018500,-115.540333,8.283,5.41,mw,33.25,-115.75,212.758376,16.998607,8.519485,12.759046,0.558430,3.833484,4,2012,8,2012-08,31.25,35.25,-117.75,-113.75,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -117.75), (31.25, -117.25), (31.25, -...",[2012-08],2012-08-01
32591,2012-10-21,06:55:09.510Z,36.309667,-120.856000,8.619,5.29,mw,36.25,-120.75,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2012,10,2012-10,34.75,37.75,-122.25,-119.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -122.25), (34.75, -121.75), (34.75, -...",[2012-10],2012-10-01
32624,2012-12-14,10:36:01.590Z,31.095000,-119.660000,13.000,6.30,mww,31.25,-119.75,526.340352,24.988106,12.523720,18.755913,0.820897,9.483610,9,2012,12,2012-12,26.75,35.75,-124.25,-115.25,"[26.75, 27.25, 27.75, 28.25, 28.75, 29.25, 29....","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [26.75, 27.25, 27.75, 28.25, 28....","[(26.75, -124.25), (26.75, -123.75), (26.75, -...",[2012-12],2012-12-01
32674,2013-02-13,00:10:14.393Z,38.022200,-118.055300,7.500,5.10,ml,38.25,-118.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2013,2,2013-02,36.75,39.75,-119.75,-116.75,"[36.75, 37.25, 37.75, 38.25, 38.75, 39.25, 39.75]","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [36.75, 37.25, 37.75, 38.25, 38....","[(36.75, -119.75), (36.75, -119.25), (36.75, -...",[2013-02],2013-02-01
32765,2013-05-24,03:47:08.180Z,40.191833,-121.059500,7.968,5.69,mw,40.25,-121.25,282.908937,19.189044,9.617304,14.403174,0.630389,5.097458,5,2013,5,2013-05,37.75,42.75,-123.75,-118.75,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -123.75), (37.75, -123.25), (37.75, -...",[2013-05],2013-05-01
33022,2014-03-29,04:09:42.170Z,33.932500,-117.915833,5.090,5.10,mw,33.75,-117.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2014,3,2014-03,32.25,35.25,-119.25,-116.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -119.25), (32.25, -118.75), (32.25, -...",[2014-03],2014-03-01
33142,2014-08-24,10:20:44.070Z,38.215167,-122.312333,11.120,6.02,mw,38.25,-122.25,395.828141,22.135704,11.094132,16.614918,0.727191,7.132039,7,2014,8,2014-08,34.75,41.75,-125.75,-118.75,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37....","[-125.75, -125.25, -124.75, -124.25, -123.75, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -125.75), (34.75, -125.25), (34.75, -...",[2014-08],2014-08-01
33411,2015-01-28,21:08:53.710Z,40.317833,-124.606667,16.881,5.72,mw,40.25,-124.75,291.680010,19.439869,9.743014,14.591442,0.638629,5.255496,5,2015,1,2015-01,37.75,42.75,-127.25,-122.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -127.25), (37.75, -126.75), (37.75, -...",[2015-01],2015-01-01
33505,2015-05-22,18:47:42.980Z,37.292500,-114.654600,4.000,5.30,ml,37.25,-114.75,190.224594,16.208146,8.123316,12.165731,0.532462,3.427470,3,2015,5,2015-05,35.75,38.75,-116.25,-113.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -116.25), (35.75, -115.75), (35.75, -...",[2015-05],2015-05-01
33832,2016-06-10,08:04:38.700Z,33.431500,-116.442667,12.310,5.19,mw,33.25,-116.25,170.077423,15.454442,7.745569,11.600006,0.507702,3.064458,3,2016,6,2016-06,31.75,34.75,-117.75,-114.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.75), (31.75, -117.25), (31.75, -...",[2016-06],2016-06-01
33882,2016-08-10,02:57:17.510Z,39.329333,-122.801833,14.450,5.09,mw,39.25,-122.75,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2016,8,2016-08,37.75,40.75,-124.25,-121.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40.75]","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -124.25), (37.75, -123.75), (37.75, -...",[2016-08],2016-08-01
33978,2016-12-14,16:41:05.530Z,38.822167,-122.841333,1.480,5.01,mw,38.75,-122.75,141.607634,14.295960,7.164953,10.730457,0.469644,2.551489,3,2016,12,2016-12,37.25,40.25,-124.25,-121.25,"[37.25, 37.75, 38.25, 38.75, 39.25, 39.75, 40.25]","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [37.25, 37.75, 38.25, 38.75, 39....","[(37.25, -124.25), (37.25, -123.75), (37.25, -...",[2016-12],2016-12-01

In [28]:
# prompt: get only the year and month from anomaly_month as label the column as anomaly_month

# Extract year and month from the 'anomaly_time' column
catalog_data['anomaly_month'] = catalog_data['anomaly_time'].dt.strftime('%Y-%m')

In [29]:
catalog_data

,date,time,latitude,longitude,depth,mag,magtype,lat_grid,lon_grid,D_eps,T_plus,T_minus,T,T_plus_months,D_eps_divided,D_eps_divided_rounded,year,month,year_month,lat_min,lat_max,lon_min,lon_max,lat_range,lon_range,range,coordinates,time_period,anomaly_time,anomaly_month
27321,2002-06-17,16:55:07.680Z,40.809833,-124.552000,17.195,5.20,mw,40.75,-124.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2002,6,2002-06,39.25,42.25,-126.25,-123.25,"[39.25, 39.75, 40.25, 40.75, 41.25, 41.75, 42.25]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.25, 39.75, 40.25, 40.75, 41....","[(39.25, -126.25), (39.25, -125.75), (39.25, -...",[2002-06],2002-06-01,2002-06
27743,2003-12-22,19:15:56.240Z,35.700500,-121.100500,8.382,6.50,mw,35.75,-121.25,645.158861,27.247919,13.656309,20.452114,0.895135,11.624484,12,2003,12,2003-12,29.75,41.75,-127.25,-115.25,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -127.25), (29.75, -126.75), (29.75, -...",[2003-12],2003-12-01,2003-12
28206,2004-09-18,23:02:17.750Z,38.009500,-118.678500,3.355,5.40,mw,38.25,-118.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -...",[2004-09],2004-09-01,2004-09
28210,2004-09-18,23:43:41.490Z,38.023333,-118.658000,0.431,5.35,mw,38.25,-118.75,200.155103,16.562784,8.301056,12.431920,0.544112,3.606398,4,2004,9,2004-09,36.25,40.25,-120.75,-116.75,"[36.25, 36.75, 37.25, 37.75, 38.25, 38.75, 39....","[-120.75, -120.25, -119.75, -119.25, -118.75, ...","{'lat_range': [36.25, 36.75, 37.25, 37.75, 38....","[(36.25, -120.75), (36.25, -120.25), (36.25, -...",[2004-09],2004-09-01,2004-09
28244,2004-09-28,17:15:24.250Z,35.818167,-120.366000,8.136,5.97,mw,35.75,-120.25,376.189497,21.661740,10.856587,16.259164,0.711621,6.778189,7,2004,9,2004-09,32.25,39.25,-123.75,-116.75,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -123.75), (32.25, -123.25), (32.25, -...",[2004-09],2004-09-01,2004-09
28260,2004-09-29,17:10:04.030Z,35.953667,-120.502167,10.772,5.00,mw,35.75,-120.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2004,9,2004-09,34.25,37.25,-122.25,-119.25,"[34.25, 34.75, 35.25, 35.75, 36.25, 36.75, 37.25]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.25, 34.75, 35.25, 35.75, 36....","[(34.25, -122.25), (34.25, -121.75), (34.25, -...",[2004-09],2004-09-01,2004-09
28261,2004-09-29,22:54:54.240Z,35.389833,-118.623500,2.788,5.03,mw,35.25,-118.75,144.519572,14.420268,7.227254,10.823761,0.473728,2.603956,3,2004,9,2004-09,33.75,36.75,-120.25,-117.25,"[33.75, 34.25, 34.75, 35.25, 35.75, 36.25, 36.75]","[-120.25, -119.75, -119.25, -118.75, -118.25, ...","{'lat_range': [33.75, 34.25, 34.75, 35.25, 35....","[(33.75, -120.25), (33.75, -119.75), (33.75, -...",[2004-09],2004-09-01,2004-09
28485,2005-06-12,15:41:46.520Z,33.532500,-116.566667,13.051,5.20,mw,33.75,-116.75,171.817212,15.521487,7.779171,11.650329,0.509904,3.095806,3,2005,6,2005-06,32.25,35.25,-118.25,-115.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -118.25), (32.25, -117.75), (32.25, -...",[2005-06],2005-06-01,2005-06
28573,2005-09-02,01:27:19.590Z,33.153333,-115.646333,1.207,5.08,mw,33.25,-115.75,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2005,9,2005-09,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -...",[2005-09],2005-09-01,2005-09
28815,2006-05-24,04:20:26.010Z,32.306667,-115.227833,6.006,5.37,mw,32.25,-115.25,204.270977,16.706802,8.373236,12.540019,0.548844,3.680558,4,2006,5,2006-05,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -...",[2006-05],2006-05-01,2006-05
29045,2007-02-26,12:21:02.140Z,40.642000,-124.870000,4.957,5.40,mh,40.75,-124.75,210.604025,16.925181,8.482685,12.703933,0.556018,3.794667,4,2007,2,2007-02,38.75,42.75,-126.75,-122.75,"[38.75, 39.25, 39.75, 40.25, 40.75, 41.25, 41....","[-126.75, -126.25, -125.75, -125.25, -124.75, ...","{'lat_range': [38.75, 39.25, 39.75, 40.25, 40....","[(38.75, -126.75), (38.75, -126.25), (38.75, -...",[2007-02],2007-02-01,2007-02
29147,2007-06-25,02:32:24.620Z,41.115500,-124.824500,2.563,5.00,mw,41.25,-124.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2007,6,2007-06,39.75,42.75,-126.25,-123.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-126.25, -125.75, -125.25, -124.75, -124.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -126.25), (39.75, -125.75), (39.75, -...",[2007-06],2007-06-01,2007-06
29225,2007-10-31,03:04:54.810Z,37.433500,-121.774333,9.741,5.45,mw,37.25,-121.75,221.598424,17.295508,8.668288,12.981898,0.568184,3.992764,4,2007,10,2007-10,35.25,39.25,-123.75,-119.75,"[35.25, 35.75, 36.25, 36.75, 37.25, 37.75, 38....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [35.25, 35.75, 36.25, 36.75, 37....","[(35.25, -123.75), (35.25, -123.25), (35.25, -...",[2007-10],2007-10-01,2007-10
29278,2008-02-09,07:12:04.550Z,32.359500,-115.277333,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2008-02],2008-02-01,2008-02
29290,2008-02-11,18:29:30.530Z,32.327167,-115.256833,6.001,5.10,mw,32.25,-115.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2008-02],2008-02-01,2008-02
29333,2008-02-19,22:41:29.660Z,32.432500,-115.313000,6.006,5.01,mw,32.25,-115.25,141.607634,14.295960,7.164953,10.730457,0.469644,2.551489,3,2008,2,2008-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2008-02],2008-02-01,2008-02
29343,2008-02-21,14:16:02.821Z,41.144400,-114.872100,7.900,5.90,mw,41.25,-114.75,350.321399,21.015191,10.532545,15.773868,0.690381,6.312097,6,2008,2,2008-02,38.25,44.25,-117.75,-111.75,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -117.75), (38.25, -117.25), (38.25, -...",[2008-02],2008-02-01,2008-02
29347,2008-02-21,14:34:55.538Z,41.137000,-114.839800,0.000,5.10,ml,41.25,-114.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,2,2008-02,39.75,42.75,-116.25,-113.25,"[39.75, 40.25, 40.75, 41.25, 41.75, 42.25, 42.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [39.75, 40.25, 40.75, 41.25, 41....","[(39.75, -116.25), (39.75, -115.75), (39.75, -...",[2008-02],2008-02-01,2008-02
29543,2008-04-26,06:40:10.453Z,39.523100,-119.939300,2.800,5.10,ml,39.75,-119.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2008,4,2008-04,38.25,41.25,-121.25,-118.25,"[38.25, 38.75, 39.25, 39.75, 40.25, 40.75, 41.25]","[-121.25, -120.75, -120.25, -119.75, -119.25, ...","{'lat_range': [38.25, 38.75, 39.25, 39.75, 40....","[(38.25, -121.25), (38.25, -120.75), (38.25, -...",[2008-04],2008-04-01,2008-04
29652,2008-07-29,18:42:15.670Z,33.948500,-117.766333,15.503,5.44,mw,33.75,-117.75,219.354560,17.220800,8.630845,12.925823,0.565729,3.952334,4,2008,7,2008-07,31.75,35.75,-119.75,-115.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34....","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -119.75), (31.75, -119.25), (31.75, -...",[2008-07],2008-07-01,2008-07
29760,2008-12-06,04:18:42.850Z,34.813333,-116.418833,6.370,5.06,mw,34.75,-116.25,149.000137,14.608759,7.321724,10.965241,0.479920,2.684687,3,2008,12,2008-12,33.25,36.25,-117.75,-114.75,"[33.25, 33.75, 34.25, 34.75, 35.25, 35.75, 36.25]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [33.25, 33.75, 34.25, 34.75, 35....","[(33.25, -117.75), (33.25, -117.25), (33.25, -...",[2008-12],2008-12-01,2008-12
30001,2009-09-19,22:55:17.840Z,32.370667,-115.261167,9.987,5.08,mw,32.25,-115.25,152.064090,14.735787,7.385388,11.060588,0.484093,2.739894,3,2009,9,2009-09,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2009-09],2009-09-01,2009-09
30010,2009-10-01,10:01:24.670Z,36.387833,-117.858667,3.985,5.00,mw,36.25,-117.75,140.173742,14.234209,7.134004,10.684106,0.467615,2.525653,3,2009,10,2009-10,34.75,37.75,-119.25,-116.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -119.25), (34.75, -118.75), (34.75, -...",[2009-10],2009-10-01,2009-10
30114,2009-12-30,18:48:57.330Z,32.464000,-115.189167,5.971,5.80,mw,32.25,-115.25,316.421997,20.124882,10.086334,15.105608,0.661133,5.701297,6,2009,12,2009-12,29.25,35.25,-118.25,-112.25,"[29.25, 29.75, 30.25, 30.75, 31.25, 31.75, 32....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [29.25, 29.75, 30.25, 30.75, 31....","[(29.25, -118.25), (29.25, -117.75), (29.25, -...",[2009-12],2009-12-01,2009-12
30263,2010-04-04,22:40:42.360Z,32.286167,-115.295333,9.987,7.20,mw,32.25,-115.25,1315.426742,36.892096,18.489848,27.690972,1.211961,23.701383,24,2010,4,2010-04,20.25,44.25,-127.25,-103.25,"[20.25, 20.75, 21.25, 21.75, 22.25, 22.75, 23....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [20.25, 20.75, 21.25, 21.75, 22....","[(20.25, -127.25), (20.25, -126.75), (20.25, -...",[2010-04],2010-03-01,2010-03
30264,2010-04-04,22:43:00.430Z,32.453333,-115.632000,9.981,5.26,ml,32.25,-115.75,182.636118,15.929910,7.983868,11.956889,0.523322,3.290741,3,2010,4,2010-04,30.75,33.75,-117.25,-114.25,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -117.25), (30.75, -116.75), (30.75, -...",[2010-04],2010-04-01,2010-04
30270,2010-04-04,22:50:17.120Z,32.098667,-115.048167,10.011,5.70,mw,32.25,-115.25,285.802923,19.272290,9.659026,14.465658,0.633124,5.149602,5,2010,4,2010-04,29.75,34.75,-117.75,-112.75,"[29.75, 30.25, 30.75, 31.25, 31.75, 32.25, 32....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [29.75, 30.25, 30.75, 31.25, 31....","[(29.75, -117.75), (29.75, -117.25), (29.75, -...",[2010-04],2010-04-01,2010-04
30278,2010-04-04,23:15:14.240Z,32.300000,-115.259500,9.987,5.43,mw,32.25,-115.25,217.133417,17.146415,8.593564,12.869990,0.563286,3.912314,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -...",[2010-04],2010-04-01,2010-04
30288,2010-04-04,23:25:07.190Z,32.266167,-115.292500,9.987,5.38,mw,32.25,-115.25,206.360545,16.779280,8.409561,12.594421,0.551225,3.718208,4,2010,4,2010-04,30.25,34.25,-117.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -117.25), (30.25, -116.75), (30.25, -...",[2010-04],2010-04-01,2010-04
30319,2010-04-05,00:07:07.920Z,31.978833,-115.134167,9.994,5.22,ml,31.75,-115.25,175.350362,15.656451,7.846814,11.751632,0.514338,3.159466,3,2010,4,2010-04,30.25,33.25,-116.75,-113.75,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33.25]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -116.75), (30.25, -116.25), (30.25, -...",[2010-04],2010-04-01,2010-04
30883,2010-04-08,16:44:25.010Z,32.164667,-115.268333,9.985,5.29,mw,32.25,-115.25,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2010,4,2010-04,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2010-04],2010-04-01,2010-04
31417,2010-06-15,04:26:58.240Z,32.705000,-115.911333,8.756,5.71,mw,32.75,-115.75,288.726514,19.355898,9.700929,14.528414,0.635871,5.202280,5,2010,6,2010-06,30.25,35.25,-118.25,-113.25,"[30.25, 30.75, 31.25, 31.75, 32.25, 32.75, 33....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [30.25, 30.75, 31.25, 31.75, 32....","[(30.25, -118.25), (30.25, -117.75), (30.25, -...",[2010-06],2010-06-01,2010-06
31544,2010-07-07,23:53:33.480Z,33.417333,-116.474667,12.318,5.42,mw,33.25,-116.25,214.934765,17.072351,8.556444,12.814398,0.560853,3.872698,4,2010,7,2010-07,31.25,35.25,-118.25,-114.25,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-118.25, -117.75, -117.25, -116.75, -116.25, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -118.25), (31.25, -117.75), (31.25, -...",[2010-07],2010-07-01,2010-07
31957,2011-02-18,17:47:35.770Z,32.047000,-115.062167,14.929,5.09,mw,32.25,-115.25,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2011,2,2011-02,30.75,33.75,-116.75,-113.75,"[30.75, 31.25, 31.75, 32.25, 32.75, 33.25, 33.75]","[-116.75, -116.25, -115.75, -115.25, -114.75, ...","{'lat_range': [30.75, 31.25, 31.75, 32.25, 32....","[(30.75, -116.75), (30.75, -116.25), (30.75, -...",[2011-02],2011-02-01,2011-02
32499,2012-08-26,19:31:23.040Z,33.017167,-115.553667,8.323,5.32,mw,33.25,-115.75,194.136264,16.349081,8.193950,12.271515,0.537092,3.497951,3,2012,8,2012-08,31.75,34.75,-117.25,-114.25,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.25, -116.75, -116.25, -115.75, -115.25, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.25), (31.75, -116.75), (31.75, -...",[2012-08],2012-08-01,2012-08
32511,2012-08-26,20:57:58.220Z,33.018500,-115.540333,8.283,5.41,mw,33.25,-115.75,212.758376,16.998607,8.519485,12.759046,0.558430,3.833484,4,2012,8,2012-08,31.25,35.25,-117.75,-113.75,"[31.25, 31.75, 32.25, 32.75, 33.25, 33.75, 34....","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.25, 31.75, 32.25, 32.75, 33....","[(31.25, -117.75), (31.25, -117.25), (31.25, -...",[2012-08],2012-08-01,2012-08
32591,2012-10-21,06:55:09.510Z,36.309667,-120.856000,8.619,5.29,mw,36.25,-120.75,188.298416,16.138135,8.088227,12.113181,0.530162,3.392764,3,2012,10,2012-10,34.75,37.75,-122.25,-119.25,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37.75]","[-122.25, -121.75, -121.25, -120.75, -120.25, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -122.25), (34.75, -121.75), (34.75, -...",[2012-10],2012-10-01,2012-10
32624,2012-12-14,10:36:01.590Z,31.095000,-119.660000,13.000,6.30,mww,31.25,-119.75,526.340352,24.988106,12.523720,18.755913,0.820897,9.483610,9,2012,12,2012-12,26.75,35.75,-124.25,-115.25,"[26.75, 27.25, 27.75, 28.25, 28.75, 29.25, 29....","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [26.75, 27.25, 27.75, 28.25, 28....","[(26.75, -124.25), (26.75, -123.75), (26.75, -...",[2012-12],2012-12-01,2012-12
32674,2013-02-13,00:10:14.393Z,38.022200,-118.055300,7.500,5.10,ml,38.25,-118.25,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2013,2,2013-02,36.75,39.75,-119.75,-116.75,"[36.75, 37.25, 37.75, 38.25, 38.75, 39.25, 39.75]","[-119.75, -119.25, -118.75, -118.25, -117.75, ...","{'lat_range': [36.75, 37.25, 37.75, 38.25, 38....","[(36.75, -119.75), (36.75, -119.25), (36.75, -...",[2013-02],2013-02-01,2013-02
32765,2013-05-24,03:47:08.180Z,40.191833,-121.059500,7.968,5.69,mw,40.25,-121.25,282.908937,19.189044,9.617304,14.403174,0.630389,5.097458,5,2013,5,2013-05,37.75,42.75,-123.75,-118.75,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-123.75, -123.25, -122.75, -122.25, -121.75, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -123.75), (37.75, -123.25), (37.75, -...",[2013-05],2013-05-01,2013-05
33022,2014-03-29,04:09:42.170Z,33.932500,-117.915833,5.090,5.10,mw,33.75,-117.75,155.191048,14.863919,7.449607,11.156763,0.488302,2.796235,3,2014,3,2014-03,32.25,35.25,-119.25,-116.25,"[32.25, 32.75, 33.25, 33.75, 34.25, 34.75, 35.25]","[-119.25, -118.75, -118.25, -117.75, -117.25, ...","{'lat_range': [32.25, 32.75, 33.25, 33.75, 34....","[(32.25, -119.25), (32.25, -118.75), (32.25, -...",[2014-03],2014-03-01,2014-03
33142,2014-08-24,10:20:44.070Z,38.215167,-122.312333,11.120,6.02,mw,38.25,-122.25,395.828141,22.135704,11.094132,16.614918,0.727191,7.132039,7,2014,8,2014-08,34.75,41.75,-125.75,-118.75,"[34.75, 35.25, 35.75, 36.25, 36.75, 37.25, 37....","[-125.75, -125.25, -124.75, -124.25, -123.75, ...","{'lat_range': [34.75, 35.25, 35.75, 36.25, 36....","[(34.75, -125.75), (34.75, -125.25), (34.75, -...",[2014-08],2014-08-01,2014-08
33411,2015-01-28,21:08:53.710Z,40.317833,-124.606667,16.881,5.72,mw,40.25,-124.75,291.680010,19.439869,9.743014,14.591442,0.638629,5.255496,5,2015,1,2015-01,37.75,42.75,-127.25,-122.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40....","[-127.25, -126.75, -126.25, -125.75, -125.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -127.25), (37.75, -126.75), (37.75, -...",[2015-01],2015-01-01,2015-01
33505,2015-05-22,18:47:42.980Z,37.292500,-114.654600,4.000,5.30,ml,37.25,-114.75,190.224594,16.208146,8.123316,12.165731,0.532462,3.427470,3,2015,5,2015-05,35.75,38.75,-116.25,-113.25,"[35.75, 36.25, 36.75, 37.25, 37.75, 38.25, 38.75]","[-116.25, -115.75, -115.25, -114.75, -114.25, ...","{'lat_range': [35.75, 36.25, 36.75, 37.25, 37....","[(35.75, -116.25), (35.75, -115.75), (35.75, -...",[2015-05],2015-05-01,2015-05
33832,2016-06-10,08:04:38.700Z,33.431500,-116.442667,12.310,5.19,mw,33.25,-116.25,170.077423,15.454442,7.745569,11.600006,0.507702,3.064458,3,2016,6,2016-06,31.75,34.75,-117.75,-114.75,"[31.75, 32.25, 32.75, 33.25, 33.75, 34.25, 34.75]","[-117.75, -117.25, -116.75, -116.25, -115.75, ...","{'lat_range': [31.75, 32.25, 32.75, 33.25, 33....","[(31.75, -117.75), (31.75, -117.25), (31.75, -...",[2016-06],2016-06-01,2016-06
33882,2016-08-10,02:57:17.510Z,39.329333,-122.801833,14.450,5.09,mw,39.25,-122.75,153.619613,14.799714,7.417428,11.108571,0.486193,2.767921,3,2016,8,2016-08,37.75,40.75,-124.25,-121.25,"[37.75, 38.25, 38.75, 39.25, 39.75, 40.25, 40.75]","[-124.25, -123.75, -123.25, -122.75, -122.25, ...","{'lat_range': [37.75, 38.25, 38.75, 39.25, 39....","[(37.75, -124.25), (37.75, -123.75), (37.75, -...",[2016-08],2016-08-01,2016-08

In [41]:
"""
check
# prompt: get the total number of elements in  every row of coordinates of catalog_data and sum them to get one value

# Calculate the total number of elements in each row of the 'coordinates' column
catalog_data['num_coordinates'] = catalog_data['coordinates'].apply(len)

# Calculate the sum of all elements in the 'num_coordinates' column
total_coordinates = catalog_data['num_coordinates'].sum()

print(f"The total number of coordinates across all rows: {total_coordinates}")
"""

The total number of coordinates across all rows: 12230

In [34]:
!pip install netCDF4
from netCDF4 import Dataset
# Load the GRACE Mascon data from Google Drive
netcdf_file_path = '/content/drive/MyDrive/grace_data/GRACE_Mascon_data.nc'
with Dataset(netcdf_file_path, mode='r') as nc_file:
    # List all variables in the NetCDF file
    print("Variables in GRACE Mascon NetCDF file:")
    print(nc_file.variables.keys())

    # Extract data for specific variables (example: lwe_thickness)
    lwe_thickness = nc_file.variables['lwe_thickness'][:]
    latitudes = nc_file.variables['lat'][:]
    longitudes = nc_file.variables['lon'][:]

    # Convert longitudes from [0, 360] to [-180, 180] range
    longitudes = np.where(longitudes > 180, longitudes - 360, longitudes)
    times = nc_file.variables['time'][:]

    # Display basic information about the extracted data
    print("LWE Thickness Data Shape:", lwe_thickness.shape)
    print("Latitude Data Shape:", latitudes.shape)
    print("Longitude Data Shape:", longitudes.shape)
    print("Time Data Shape:", times.shape)

    # Step 8: Add year_month to GRACE data
from datetime import datetime, timedelta

# Convert time to datetime format and create year_month column
time_reference = datetime(2002, 1, 1)  # Assuming GRACE times start from January 2002
grace_dates = [time_reference + timedelta(days=int(t)) for t in times]
grace_year_month = pd.to_datetime(grace_dates).to_period('M')

# Step 8: Filter GRACE data for California region only
california_lat_min, california_lat_max = 31, 42
california_lon_min, california_lon_max = -125, -114

# Filter GRACE data for California latitudes and longitudes
lat_indices = np.where((latitudes >= california_lat_min) & (latitudes <= california_lat_max))[0]
lon_indices = np.where((longitudes >= california_lon_min) & (longitudes <= california_lon_max))[0]

# Extract the filtered data
filtered_latitudes = latitudes[lat_indices]
filtered_longitudes = longitudes[lon_indices]
filtered_lwe_thickness = lwe_thickness[:, lat_indices, :][:, :, lon_indices]

# Convert time to datetime format and create year_month column
time_reference = datetime(2002, 1, 1)  # Assuming GRACE times start from January 2002
grace_dates = [time_reference + timedelta(days=int(t)) for t in times]
grace_year_month = pd.to_datetime(grace_dates).to_period('M')

# Create a DataFrame for filtered GRACE data
filtered_grace_data_list = []
for time_idx, year_month in enumerate(grace_year_month):
    for lat_idx, latitude in enumerate(filtered_latitudes):
        for lon_idx, longitude in enumerate(filtered_longitudes):
            lwe_value = filtered_lwe_thickness[time_idx, lat_idx, lon_idx]
            filtered_grace_data_list.append({
                'year_month': year_month,
                'latitude': latitude,
                'longitude': longitude,
                'lwe_thickness': lwe_value
            })

# Convert list of dictionaries to DataFrame
grace_data = pd.DataFrame(filtered_grace_data_list)

Collecting netCDF4
  Downloading netCDF4-1.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting cftime (from netCDF4)
  Downloading cftime-1.6.4.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from netCDF4) (2024.8.30)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from netCDF4) (1.26.4)
Downloading netCDF4-1.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 49.0 MB/s eta 0:00:00
Downloading cftime-1.6.4.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 43.6 MB/s eta 0:00:00
Installing collected packages: cftime, netCDF4
Successfully installed cftime-1.6.4.post1 netCDF4-1.7.2
Variables in GRACE Mascon NetCDF file:
dict_keys(['lon', 'lat', 'time', 'land_mask', 'lwe_thickness', 'lon_bounds', 'lat_bounds', 'time_bounds'])
LWE Thickness Data Shape: (231, 360, 720)
Latitude Data Shape: (360,)
Longitude Data Shape: (720,)
Time Data Shape: (231,)

In [36]:
# prompt: merge the latitude and longitude of grace_data into one column called grace_coordinates

# Create the 'grace_coordinates' column by combining latitude and longitude
grace_data['grace_coordinates'] = grace_data['latitude'].astype(str) + ', ' + grace_data['longitude'].astype(str)

In [ ]:
grace_data[grace_data['year_month']] == '2002-04'

KeyboardInterrupt

In [59]:
# prompt: coordinates column of catalog_data contains list of coordinates. I want to iterate over the coordinates list for each row of catalog_data and then based on individual coordinate value filter the grace_data
cnt = 0;
# Iterate through each row of catalog_data
for index, row in catalog_data.iterrows():
    coordinates = row['coordinates']
    anomaly_month = row['anomaly_month']  # Access the anomaly_month for the current row
    print(anomaly_month)
    # Filter grace_data based on the coordinates and anomaly_month
    filtered_grace_data = grace_data[grace_data['year_month'] == anomaly_month]

    print(filtered_grace_data)
    break;
    """
    for coordinate in coordinates:
      lat, lon = coordinate
      # Filter grace_data for the current coordinate
      coordinate_grace_data = filtered_grace_data[
          (filtered_grace_data['latitude'] == lat) & (filtered_grace_data['longitude'] == lon)
      ]
      print(coordinate_grace_data)
      cnt += 1;
      # Now you have coordinate_grace_data which contains data for the specific coordinate
      # Perform further analysis or processing on coordinate_grace_data as needed.
      # For example, you can print the data:
      #print(f"GRACE data for coordinate ({lat}, {lon}) and month {anomaly_month}:")
    break;
    """
cnt #cnt to check if the number of rows matched the coordinates.

      # Or you can calculate statistics, plot the data, etc.

2002-06
Empty DataFrame
Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
Index: []

0

In [46]:
# prompt: change the code in the above cell and create a df out of all the values of coordinate_grace_data

import pandas as pd

# Assuming 'coordinate_grace_data' is defined within the loop as in your original code

# Initialize an empty list to store DataFrames
all_coordinate_grace_data = []
cnt = 0;
# Iterate through each row of catalog_data
for index, row in catalog_data.iterrows():
    coordinates = row['coordinates']
    anomaly_month = row['anomaly_month']  # Access the anomaly_month for the current row

    # Filter grace_data based on the coordinates and anomaly_month
    filtered_grace_data = grace_data[grace_data['year_month'] == anomaly_month]

    for coordinate in coordinates:
      lat, lon = coordinate
      # Filter grace_data for the current coordinate
      coordinate_grace_data = filtered_grace_data[
          (filtered_grace_data['latitude'] == lat) & (filtered_grace_data['longitude'] == lon)
      ]

      # Append the current coordinate_grace_data to the list
      all_coordinate_grace_data.append(coordinate_grace_data)
      cnt += 1;
# Concatenate all the DataFrames in the list into a single DataFrame
final_df = pd.concat(all_coordinate_grace_data, ignore_index=True)
print(cnt)
# Now 'final_df' contains all the data from 'coordinate_grace_data' across all iterations
#final_df

12230

In [50]:
all_coordinate_grace_data

[Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8228    2003-12     31.25    -124.75      -0.047921    31.25, -124.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8229    2003-12     31.25    -124.25      -0.047921    31.25, -124.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8230    2003-12     31.25    -123.75      -0.320428    31.25, -123.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8231    2003-12     31.25    -123.25      -0.320428    31.25, -123.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8232    2003-12     31.25    -122.75      -0.320428    31.25, -122.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8233    2003-12     31.25    -122.25      -0.709916    31.25, -122.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8234    2003-12     31.25    -121.75      -0.709916    31.25, -121.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8235    2003-12     31.25    -121.25      -0.905695    31.25, -121.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8236    2003-12     31.25    -120.75      -0.905695    31.25, -120.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8237    2003-12     31.25    -120.25      -1.113388    31.25, -120.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8238    2003-12     31.25    -119.75      -1.113388    31.25, -119.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8239    2003-12     31.25    -119.25      -1.113388    31.25, -119.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8240    2003-12     31.25    -118.75      -0.826178    31.25, -118.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8241    2003-12     31.25    -118.25      -0.826178    31.25, -118.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8242    2003-12     31.25    -117.75      -1.092975    31.25, -117.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8243    2003-12     31.25    -117.25      -1.092975    31.25, -117.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8244    2003-12     31.25    -116.75      -0.952527    31.25, -116.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8245    2003-12     31.25    -116.25      -1.904539    31.25, -116.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8246    2003-12     31.25    -115.75      -2.084318    31.25, -115.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8247    2003-12     31.25    -115.25      -3.247131    31.25, -115.25,
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
 Empty DataFrame
 Columns: [year_month, latitude, longitude, lwe_thickness, grace_coordinates]
 Index: [],
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8250    2003-12     31.75    -124.75      -0.072843    31.75, -124.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8251    2003-12     31.75    -124.25      -0.072843    31.75, -124.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8252    2003-12     31.75    -123.75      -0.164293    31.75, -123.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8253    2003-12     31.75    -123.25      -0.164293    31.75, -123.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8254    2003-12     31.75    -122.75      -0.678535    31.75, -122.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8255    2003-12     31.75    -122.25      -0.678535    31.75, -122.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8256    2003-12     31.75    -121.75      -0.678535    31.75, -121.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8257    2003-12     31.75    -121.25      -0.820008    31.75, -121.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8258    2003-12     31.75    -120.75      -0.820008    31.75, -120.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8259    2003-12     31.75    -120.25      -0.981506    31.75, -120.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8260    2003-12     31.75    -119.75      -0.981506    31.75, -119.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8261    2003-12     31.75    -119.25      -0.981506    31.75, -119.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8262    2003-12     31.75    -118.75      -1.044097    31.75, -118.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8263    2003-12     31.75    -118.25      -1.044097    31.75, -118.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8264    2003-12     31.75    -117.75      -0.853818    31.75, -117.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8265    2003-12     31.75    -117.25      -0.853818    31.75, -117.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8266    2003-12     31.75    -116.75      -0.840531    31.75, -116.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8267    2003-12     31.75    -116.25      -1.356177    31.75, -116.25,
      year_month  latitude  longitude  lwe_thickness grace_coordinates
 8268    2003-12     31.75    -115.75      -1.516073    31.75, -115.75,
      year_month  latitude  longitude  lwe_thickness grace_coordinates

In [ ]:
# prompt: coordinates column of catalog_data contains list of coordinates. I want to iterate over the coordinates list for each row of catalog_data and then based on individual coordinate value filter the grace_data
cnt =
# Iterate through each row of catalog_data
for index, row in catalog_data.iterrows():
    coordinates = row['coordinates']
    anomaly_month = row['anomaly_month']  # Access the anomaly_month for the current row

    # Filter grace_data based on the coordinates and anomaly_month
    filtered_grace_data = grace_data[grace_data['year_month'] == anomaly_month]

    for coordinate in coordinates:
      lat, lon = coordinate
      # Filter grace_data for the current coordinate
      coordinate_grace_data = filtered_grace_data[
          (filtered_grace_data['latitude'] == lat) & (filtered_grace_data['longitude'] == lon)
      ]

      # Now you have coordinate_grace_data which contains data for the specific coordinate
      # Perform further analysis or processing on coordinate_grace_data as needed.
      # For example, you can print the data:
      print(f"GRACE data for coordinate ({lat}, {lon}) and month {anomaly_month}:")
coordinate_grace_data

      # Or you can calculate statistics, plot the data, etc.

In [32]:
# Load the GRACE Mascon data from Google Drive
netcdf_file_path = '/content/drive/MyDrive/grace_data/GRACE_Mascon_data.nc'
with Dataset(netcdf_file_path, mode='r') as nc_file:
    # List all variables in the NetCDF file
    print("Variables in GRACE Mascon NetCDF file:")
    print(nc_file.variables.keys())

    # Extract data for specific variables (example: lwe_thickness)
    lwe_thickness = nc_file.variables['lwe_thickness'][:]
    latitudes = nc_file.variables['lat'][:]
    longitudes = nc_file.variables['lon'][:]

    # Convert longitudes from [0, 360] to [-180, 180] range
    longitudes = np.where(longitudes > 180, longitudes - 360, longitudes)
    times = nc_file.variables['time'][:]

    # Display basic information about the extracted data
    print("LWE Thickness Data Shape:", lwe_thickness.shape)
    print("Latitude Data Shape:", latitudes.shape)
    print("Longitude Data Shape:", longitudes.shape)
    print("Time Data Shape:", times.shape)

    # Step 8: Add year_month to GRACE data
from datetime import datetime, timedelta

# Convert time to datetime format and create year_month column
time_reference = datetime(2002, 1, 1)  # Assuming GRACE times start from January 2002
grace_dates = [time_reference + timedelta(days=int(t)) for t in times]
grace_year_month = pd.to_datetime(grace_dates).to_period('M')

# Step 8: Filter GRACE data for California region only
california_lat_min, california_lat_max = 31, 42
california_lon_min, california_lon_max = -125, -114

# Filter GRACE data for California latitudes and longitudes
lat_indices = np.where((latitudes >= california_lat_min) & (latitudes <= california_lat_max))[0]
lon_indices = np.where((longitudes >= california_lon_min) & (longitudes <= california_lon_max))[0]

# Extract the filtered data
filtered_latitudes = latitudes[lat_indices]
filtered_longitudes = longitudes[lon_indices]
filtered_lwe_thickness = lwe_thickness[:, lat_indices, :][:, :, lon_indices]

# Convert time to datetime format and create year_month column
time_reference = datetime(2002, 1, 1)  # Assuming GRACE times start from January 2002
grace_dates = [time_reference + timedelta(days=int(t)) for t in times]
grace_year_month = pd.to_datetime(grace_dates).to_period('M')

# Create a DataFrame for filtered GRACE data
filtered_grace_data_list = []
for time_idx, year_month in enumerate(grace_year_month):
    for lat_idx, latitude in enumerate(filtered_latitudes):
        for lon_idx, longitude in enumerate(filtered_longitudes):
            lwe_value = filtered_lwe_thickness[time_idx, lat_idx, lon_idx]
            filtered_grace_data_list.append({
                'year_month': year_month,
                'latitude': latitude,
                'longitude': longitude,
                'lwe_thickness': lwe_value
            })

# Convert list of dictionaries to DataFrame
grace_data = pd.DataFrame(filtered_grace_data_list)

NameError: name 'Dataset' is not defined

In [ ]:
# Approach 2

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
!pip install netCDF4


# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load the catalog data from Google Drive
file_path = '/content/drive/MyDrive/grace_data/catalog.txt'
catalog_data = pd.read_csv(file_path, delim_whitespace=True)

# OLD CODE START

# OLD CODE END

# New Step 1: Convert the date column to datetime format
catalog_data['date'] = pd.to_datetime(catalog_data['date'], format='%Y-%m-%d')

# Filter seismic data starting from 2022-04
catalog_data = catalog_data[catalog_data['date'] >= '2002-04-01']
catalog_data = catalog_data[catalog_data['mag'] >= 3]

# New Step 2: Divide the dataset into a grid of 0.5 x 0.5 degree
# Round the latitude and longitude to the nearest 0.25 or 0.5
catalog_data['lat_grid'] = np.where((catalog_data['latitude'] % 1) < 0.5,
                                    np.floor(catalog_data['latitude']) + 0.25,
                                    np.floor(catalog_data['latitude']) + 0.75)

catalog_data['lon_grid'] = np.where((catalog_data['longitude'] % 1) < 0.5,
                                     np.floor(catalog_data['longitude']) + 0.25,
                                     np.floor(catalog_data['longitude']) + 0.75)



# New Step 3: Group by lat_grid, lon_grid, and month to get the sum of events per month
catalog_data['year_month'] = catalog_data['date'].dt.to_period('M')
events_per_month = catalog_data.groupby(['lat_grid', 'lon_grid', 'year_month']).agg(
    event_count=('year_month', 'size'),
    lat_list=('latitude', lambda x: list(x)),
    lon_list=('longitude', lambda x: list(x)),
    max_mag=('mag', 'max'),
    min_mag=('mag', 'min'),
    avg_mag=('mag', 'mean')
).reset_index()

# New Step 4: Sort the result by year_month
events_per_month = events_per_month.sort_values(by='year_month')

# Step 5: Count the number of unique grid points for each month
unique_grid_points_per_month = events_per_month.groupby('year_month')[['lat_grid', 'lon_grid']].nunique().reset_index()
unique_grid_points_per_month.rename(columns={'lat_grid': 'unique_lat_grid_count', 'lon_grid': 'unique_lon_grid_count'}, inplace=True)

# Display the number of unique grid points for each month
print("Number of unique grid points for each month:")
print(unique_grid_points_per_month)


# Display the result
events_per_month.head()

# New Step 7: Read a NetCDF file (GRACE Mascon data)
from netCDF4 import Dataset

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load the GRACE Mascon data from Google Drive
netcdf_file_path = '/content/drive/MyDrive/grace_data/GRACE_Mascon_data.nc'
with Dataset(netcdf_file_path, mode='r') as nc_file:
    # List all variables in the NetCDF file
    print("Variables in GRACE Mascon NetCDF file:")
    print(nc_file.variables.keys())

    # Extract data for specific variables (example: lwe_thickness)
    lwe_thickness = nc_file.variables['lwe_thickness'][:]
    latitudes = nc_file.variables['lat'][:]
    longitudes = nc_file.variables['lon'][:]

    # Convert longitudes from [0, 360] to [-180, 180] range
    longitudes = np.where(longitudes > 180, longitudes - 360, longitudes)
    times = nc_file.variables['time'][:]

    # Display basic information about the extracted data
    print("LWE Thickness Data Shape:", lwe_thickness.shape)
    print("Latitude Data Shape:", latitudes.shape)
    print("Longitude Data Shape:", longitudes.shape)
    print("Time Data Shape:", times.shape)

    # Step 8: Add year_month to GRACE data
from datetime import datetime, timedelta

# Convert time to datetime format and create year_month column
time_reference = datetime(2002, 1, 1)  # Assuming GRACE times start from January 2002
grace_dates = [time_reference + timedelta(days=int(t)) for t in times]
grace_year_month = pd.to_datetime(grace_dates).to_period('M')

# Step 8: Filter GRACE data for California region only
california_lat_min, california_lat_max = 31, 42
california_lon_min, california_lon_max = -125, -114

# Filter GRACE data for California latitudes and longitudes
lat_indices = np.where((latitudes >= california_lat_min) & (latitudes <= california_lat_max))[0]
lon_indices = np.where((longitudes >= california_lon_min) & (longitudes <= california_lon_max))[0]

# Extract the filtered data
filtered_latitudes = latitudes[lat_indices]
filtered_longitudes = longitudes[lon_indices]
filtered_lwe_thickness = lwe_thickness[:, lat_indices, :][:, :, lon_indices]

# Convert time to datetime format and create year_month column
time_reference = datetime(2002, 1, 1)  # Assuming GRACE times start from January 2002
grace_dates = [time_reference + timedelta(days=int(t)) for t in times]
grace_year_month = pd.to_datetime(grace_dates).to_period('M')

# Create a DataFrame for filtered GRACE data
filtered_grace_data_list = []
for time_idx, year_month in enumerate(grace_year_month):
    for lat_idx, latitude in enumerate(filtered_latitudes):
        for lon_idx, longitude in enumerate(filtered_longitudes):
            lwe_value = filtered_lwe_thickness[time_idx, lat_idx, lon_idx]
            filtered_grace_data_list.append({
                'year_month': year_month,
                'latitude': latitude,
                'longitude': longitude,
                'lwe_thickness': lwe_value
            })

# Convert list of dictionaries to DataFrame
grace_data = pd.DataFrame(filtered_grace_data_list)

# Ensure correct column names for grace_data
# No need to rename columns, keep as 'latitude' and 'longitude'

# Step 9: Display columns for debugging
print("GRACE Data Columns:")
print(grace_data.columns.tolist())
print("Events per Month Columns:")
print(events_per_month.columns.tolist())
print(events_per_month.columns)

# Step 9: Based on the printed column names, adjust the merge operation
grace_filtered_data = grace_data.merge(events_per_month,
                                       left_on=['latitude', 'longitude', 'year_month'],
                                       right_on=['lat_grid', 'lon_grid', 'year_month'],
                                       how='inner')

# Display the filtered GRACE Data
grace_filtered_df = grace_filtered_data[['latitude', 'longitude', 'year_month', 'lwe_thickness']]
print("Filtered GRACE Data:")
print(grace_filtered_df)

Collecting netCDF4
  Downloading netCDF4-1.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting cftime (from netCDF4)
  Downloading cftime-1.6.4.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from netCDF4) (2024.8.30)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from netCDF4) (1.26.4)
Downloading netCDF4-1.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 50.5 MB/s eta 0:00:00
Downloading cftime-1.6.4.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 42.1 MB/s eta 0:00:00
Installing collected packages: cftime, netCDF4
Successfully installed cftime-1.6.4.post1 netCDF4-1.7.2
Mounted at /content/drive

<ipython-input-5-336d50d7b15a>:15: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  catalog_data = pd.read_csv(file_path, delim_whitespace=True)

Number of unique grid points for each month:
    year_month  unique_lat_grid_count  unique_lon_grid_count
0      2002-04                      7                      8
1      2002-05                     12                     10
2      2002-06                      8                      9
3      2002-07                     10                     12
4      2002-08                      9                     10
..         ...                    ...                    ...
256    2023-08                     12                     14
257    2023-09                     10                     11
258    2023-10                     12                     12
259    2023-11                     10                     10
260    2023-12                     10                      7

[261 rows x 3 columns]
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Variables in GRACE Mascon NetCDF file:
dict_keys(['lon', 'lat', 'time', 'land_mask', 'lwe_thickness', 'lon_bounds', 'lat_bounds', 'time_bounds'])
LWE Thickness Data Shape: (231, 360, 720)
Latitude Data Shape: (360,)
Longitude Data Shape: (720,)
Time Data Shape: (231,)
GRACE Data Columns:
['year_month', 'latitude', 'longitude', 'lwe_thickness']
Events per Month Columns:
['lat_grid', 'lon_grid', 'year_month', 'event_count', 'lat_list', 'lon_list', 'max_mag', 'min_mag', 'avg_mag']
Index(['lat_grid', 'lon_grid', 'year_month', 'event_count', 'lat_list',
       'lon_list', 'max_mag', 'min_mag', 'avg_mag'],
      dtype='object')
Filtered GRACE Data:
      latitude  longitude year_month  lwe_thickness
0        31.75    -116.25    2002-04      -0.007192
1        32.25    -115.25    2002-04       2.824223
2        32.25    -114.75    2002-04       2.007574
3        34.75    -116.25    2002-04       5.708782
4        36.75    -121.75    2002-04       4.652653
...        ...        ...        ...            ...
3684     35.75    -117.75    2023-12     -37.412506
3685     36.75    -120.75    2023-12     -39.046023
3686     37.25    -118.75    2023-12     -36.929195
3687     38.75    -122.75    2023-12     -20.952386
3688     39.75    -119.75    2023-12     -22.988143

[3689 rows x 4 columns]

In [ ]:
grace_filtered_data

In [ ]:
from packaging import version
import tensorflow as tf

assert version.parse(tf.__version__) >= version.parse("2.8.0")

In [ ]:
!pip install keras_tuner
import keras_tuner as kt

def build_model(hp):
    n_hidden = hp.Int("n_hidden", min_value=0, max_value=8, default=2)
    n_neurons = hp.Int("n_neurons", min_value=16, max_value=256)
    learning_rate = hp.Float("learning_rate", min_value=1e-4, max_value=1e-2,
                             sampling="log")
    optimizer = hp.Choice("optimizer", values=["sgd", "adam"])
    if optimizer == "sgd":
        optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)
    else:
        optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

    model = tf.keras.Sequential()

    model.add(tf.keras.layers.LSTM(n_neurons, return_sequences=True, input_shape=[1, 3] , activation = "tanh"))
    for _ in range(n_hidden):
        return_sequences = True if _ < n_hidden - 1 else False
        model.add(tf.keras.layers.LSTM(n_neurons, return_sequences=return_sequences, activation="tanh"))
    model.add(tf.keras.layers.Dense(1))
    model.compile(loss="mse", optimizer=optimizer, # Changed loss to 'mse' for regression
                  metrics=["mae"]) # Changed metric to 'mae' for regression
    return model

    """
    tf.keras.layers.LSTM(n_neurons, return_sequences=True, input_shape=[None, 3] , activation = "tanh"),
    for _ in range(n_hidden):
        model.add(tf.keras.layers.LSTM(n_neurons, return_sequences=True, activation="tanh"))
    model.add(tf.keras.layers.Dense(1));
    model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer,
                  metrics=["accuracy"])
    return model
    """

In [ ]:
def fit_and_evaluate(model, train_set, valid_set, learning_rate, epochs=500):
    early_stopping_cb = tf.keras.callbacks.EarlyStopping(
        monitor="val_mae", patience=50, restore_best_weights=True)
    opt = tf.keras.optimizers.SGD(learning_rate=learning_rate, momentum=0.9)
    model.compile(loss=tf.keras.losses.Huber(), optimizer=opt, metrics=["mae"])
    history = model.fit(train_set, validation_data=valid_set, epochs=epochs,
                        callbacks=[early_stopping_cb])
    valid_loss, valid_mae = model.evaluate(valid_set)
    return valid_mae

In [ ]:
# Display the filtered GRACE Data
grace_filtered_df = grace_filtered_data[['latitude', 'longitude', 'year_month', 'lwe_thickness', 'event_count', 'max_mag', 'min_mag', 'avg_mag']]


# Step 10: Prepare data for LSTM model
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Extract predictors and target
X = grace_filtered_df[['event_count', 'year_month','max_mag', 'min_mag', 'avg_mag','lwe_thickness']]
y = grace_filtered_df[['year_month','lwe_thickness']]

X = X.set_index('year_month')

X_train = X.loc['2002-04':'2013-05', ['event_count', 'max_mag', 'avg_mag']]
X_valid = X.loc['2013-06':'2020-05', ['event_count', 'max_mag', 'avg_mag']]
X_test = X.loc['2020-06':'2024-01', ['event_count', 'max_mag', 'avg_mag']]

y_train = X.loc['2002-04':'2013-05', 'lwe_thickness']
y_valid = X.loc['2013-06':'2020-05', 'lwe_thickness']

tf.random.set_seed(42)
train_ds = tf.keras.utils.timeseries_dataset_from_array(
    X_train.to_numpy(),
    targets=y_train,
    sequence_length=1,
    batch_size=32,
    shuffle=True,
    seed=42
)
valid_ds = tf.keras.utils.timeseries_dataset_from_array(
    X_valid.to_numpy(),
    targets=y_valid,
    sequence_length=1,
    batch_size=32
)

random_search_tuner = kt.RandomSearch(
    build_model,
    objective="val_mae",
    max_trials=10,
    overwrite=True,
    directory="/content/drive/MyDrive/grace_data/tuner_srch",
    project_name="hp_search"
)

rst = random_search_tuner.search(train_ds, epochs=10, validation_data=valid_ds)

best_hp = random_search_tuner.get_best_hyperparameters()[0]
model = random_search_tuner.hypermodel.build(best_hp)
"""
deep_model = tf.keras.Sequential([
    tf.keras.layers.LSTM(32, return_sequences=True, input_shape=[None, 3]),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(1)
])
"""

fit_and_evaluate(model, train_ds , valid_ds , 1e-4 )

#,'max_mag', 'min_mag', 'avg_mag','lwe_thickness'

In [ ]:
model.summary()

In [ ]:
X_test_reshaped = X_test.to_numpy().reshape(X_test.shape[0], 1, X_test.shape[1])

In [ ]:
X_test

In [ ]:
best_hp.values

In [ ]:
# prompt: convert X_test_reshaped to a dataframe with first col as   event_count , second col as max_mag and third col as avg_mag. show first 10 rows

import pandas as pd

# Assuming X_test_reshaped is already defined as in your provided code
# X_test_reshaped = X_test.to_numpy().reshape(X_test.shape[0], 1, X_test.shape[1])

# Create a DataFrame from X_test_reshaped
X_test_df = pd.DataFrame(X_test_reshaped.reshape(X_test.shape[0], X_test.shape[1]), columns=['event_count', 'max_mag', 'avg_mag'])

# Display the first 10 rows
print(X_test_df.head(10))

NameError: name 'X_test_reshaped' is not defined

In [ ]:
# prompt: make a df from model.predict(X_test_reshaped) and name the col as lwe. show first 10 rows

# Assuming 'model' and 'X_test_reshaped' are defined as in your previous code.
import pandas as pd

predictions = model.predict(X_test_reshaped)
# Create a DataFrame from the predictions
df_predictions = pd.DataFrame(predictions, columns=['lwe'])
# Show the first 10 rows
print(df_predictions.head(10))

NameError: name 'model' is not defined

In [ ]:
model.predict(X_test_reshaped)

NameError: name 'model' is not defined